/**
 * Unified Report Ingest Engine for VLSI Studios.
 *
 * Single entry point for pasting/uploading any STA or constraint report.
 * Provides vendor auto-detection, tool metadata extraction, flow stage classification,
 * block splitting registry, and multi-file session management.
 */

import { parseTimeToken } from "./timing-engine";
import { extractCornerFromBlock } from "./corner-model";

export type TimingVendor = "synopsys" | "cadence" | "opensta" | "auto";
export type FlowStage = "synthesis" | "pnr" | "signoff" | "unknown";
export type ReportKind = "timing_path" | "si_crosstalk" | "summary_only" | "unknown";

export interface RawReportBlock {
  id: string;
  rawText: string;
  blockIndex: number;
  kind: "path" | "summary" | "header" | "unknown";
  headerHint?: {
    startpoint?: string;
    endpoint?: string;
    pathGroup?: string;
    type?: "setup" | "hold";
    clock?: string;
    corner?: string;
  };
}

export interface IngestResult {
  kind: ReportKind;
  vendor: TimingVendor;
  detectedVendor: TimingVendor;
  tool: string;
  designName?: string;
  operatingConditions?: string;
  wireloadMode?: string;
  areaMode?: string;
  stage: FlowStage;
  rawBlocks: RawReportBlock[];
  warnings: string[];
  isPs: boolean;
  headerLines: string[];
  totalRawLines: number;
}

export interface IngestReportFile {
  id: string;
  filename: string;
  text: string;
  parsedAt: number;
  result: IngestResult;
}

export interface ReportSession {
  files: IngestReportFile[];
  activeId: string;
}

// ---------------------------------------------------------------------------
// Detection logic
// ---------------------------------------------------------------------------

export function detectVendor(text: string): TimingVendor {
  const t = text.toLowerCase();
  if (
    t.includes("generated by:") ||
    t.includes("genus") ||
    t.includes("tempus") ||
    t.includes("innovus") ||
    /path\s+\d+\s*:/i.test(text) ||
    t.includes("drv adjust") ||
    t.includes("src latency")
  ) {
    return "cadence";
  }
  if (
    t.includes("opensta") ||
    /^\s*delay\s+time\s+description/im.test(text)
  ) {
    return "opensta";
  }
  if (
    t.includes("primetime") ||
    t.includes("report : timing") ||
    t.includes("path type: max") ||
    t.includes("path type: min") ||
    t.includes("slack (violated)") ||
    t.includes("slack (met)") ||
    t.includes("startpoint:") ||
    t.includes("beginpoint:")
  ) {
    return "synopsys";
  }
  return "synopsys";
}

export function detectTool(text: string, vendor: TimingVendor): string {
  const toolMatch = text.match(/Generated by:\s*(.*)/i);
  if (toolMatch) return toolMatch[1].trim();

  const verMatch = text.match(/Version:\s*(.*)/i);
  if (verMatch) return `Synopsys PrimeTime ${verMatch[1].trim()}`;

  if (/primetime/i.test(text)) return "Synopsys PrimeTime";
  if (/opensta/i.test(text)) return "OpenSTA";
  if (vendor === "cadence") return "Cadence STA Tool";
  if (vendor === "opensta") return "OpenSTA";
  return "Synopsys PrimeTime";
}

export function detectFlowStage(
  toolName: string,
  text: string,
  wireloadMode?: string
): FlowStage {
  const t = `${toolName} ${text}`.toLowerCase();
  if (
    t.includes("genus") ||
    t.includes("design compiler") ||
    t.includes("dc_shell") ||
    t.includes("yosys") ||
    t.includes("wireload") ||
    (wireloadMode && wireloadMode.length > 0)
  ) {
    return "synthesis";
  }
  if (
    t.includes("innovus") ||
    t.includes("icc2") ||
    t.includes("fusion compiler") ||
    t.includes("encounter") ||
    t.includes("place") ||
    t.includes("route")
  ) {
    return "pnr";
  }
  if (
    t.includes("tempus") ||
    t.includes("primetime") ||
    t.includes("signoff") ||
    t.includes("extracted") ||
    t.includes("spef")
  ) {
    return "signoff";
  }
  return "unknown";
}

export function detectReportKind(text: string): ReportKind {
  const t = text.toLowerCase();
  if (
    t.includes("aggressor") ||
    t.includes("crosstalk") ||
    t.includes("si delta") ||
    t.includes("delta_delay")
  ) {
    return "si_crosstalk";
  }
  if (
    t.includes("startpoint") ||
    t.includes("endpoint") ||
    t.includes("slack") ||
    /path\s+\d+/i.test(text)
  ) {
    return "timing_path";
  }
  if (t.includes("wns") || t.includes("tns") || t.includes("summary")) {
    return "summary_only";
  }
  return "unknown";
}

export function detectIsPs(text: string): boolean {
  if (/\b\(ps\)\b|\bps\b/i.test(text.slice(0, 2000))) return true;
  // Banner ns check
  if (/(?:VIOLATED|MET)\s*\(\s*-?\d+(?:\.\d+)?\s*ns\s*\)/i.test(text)) return false;
  if (/(?:VIOLATED|MET)\s*\(\s*-?\d+(?:\.\d+)?\s*ps\s*\)/i.test(text)) return true;
  return false;
}

// ---------------------------------------------------------------------------
// Block Splitter Registry
// ---------------------------------------------------------------------------

function extractHeaderHint(block: string): RawReportBlock["headerHint"] {
  let startpoint: string | undefined;
  let endpoint: string | undefined;
  let pathGroup: string | undefined;
  let type: "setup" | "hold" | undefined;
  let clock: string | undefined;

  const startMatch =
    block.match(/(?:Startpoint|Beginpoint):\s*(?:\([RF]\)\s*)?(\S+)/i) ||
    block.match(/Startpoint:\s*(.+?)\s*\(/i);
  if (startMatch) startpoint = startMatch[1].trim();

  const endMatch =
    block.match(/Endpoint:\s*(?:\([RF]\)\s*)?(\S+)/i) ||
    block.match(/Endpoint:\s*(.+?)\s*\(/i);
  if (endMatch) endpoint = endMatch[1].trim();
  if (!endpoint) {
    const t = block.match(/at pin\s+(\S+)/i);
    if (t) endpoint = t[1];
  }

  const groupMatch =
    block.match(/Path Group:\s*(\S+)/i) || block.match(/^\s*Group:\s*(\S+)/im);
  if (groupMatch) pathGroup = groupMatch[1];

  if (/\b(?:Path Type:\s*min|hold check|early)\b/i.test(block)) {
    type = "hold";
  } else if (/\b(?:Path Type:\s*max|setup check|late)\b/i.test(block)) {
    type = "setup";
  }

  const clockMatch = block.match(/Clock:\s*(?:\([RF]\)\s*)?(\S+)/i);
  if (clockMatch) clock = clockMatch[1].replace(/[()]/g, "");

  const corner = extractCornerFromBlock(block);

  return { startpoint, endpoint, pathGroup, type, clock, corner };
}

export function splitReportIntoBlocks(
  text: string,
  vendor: TimingVendor
): RawReportBlock[] {
  if (!text || !text.trim()) return [];

  const isCadence =
    vendor === "cadence" ||
    (/Path\s+\d+\s*:/i.test(text) && /Drv Adjust|Generated by:/i.test(text));

  const regex = isCadence
    ? /(?:^|\n)[ \t]*(Path\s+\d+\s*:)/gi
    : /(?:^|\n)[ \t]*(Startpoint:|Beginpoint:)/gi;

  const indices: number[] = [];
  let m: RegExpExecArray | null;
  while ((m = regex.exec(text)) !== null) {
    const at = m.index;
    const lead = text[at] === "\n" ? at + 1 : at;
    indices.push(lead);
  }

  if (indices.length === 0) {
    const alt = isCadence
      ? /(?:^|\n)[ \t]*(Startpoint:|Beginpoint:)/gi
      : /(?:^|\n)[ \t]*(Path\s+\d+\s*:)/gi;
    while ((m = alt.exec(text)) !== null) {
      const at = m.index;
      indices.push(text[at] === "\n" ? at + 1 : at);
    }
  }

  const rawStringBlocks: string[] = [];
  if (indices.length === 0) {
    rawStringBlocks.push(
      ...text
        .split(/\n\s*\n/)
        .map((b) => b.trim())
        .filter((b) => b.length > 20 && /slack|startpoint|endpoint|path\s+\d+/i.test(b))
    );
  } else {
    for (let i = 0; i < indices.length; i++) {
      const start = indices[i];
      const end = indices[i + 1] !== undefined ? indices[i + 1] : text.length;
      const block = text.slice(start, end).trim();
      if (block.length > 20) rawStringBlocks.push(block);
    }
  }

  return rawStringBlocks.map((rawText, idx) => ({
    id: `block_${idx + 1}`,
    rawText,
    blockIndex: idx,
    kind: "path",
    headerHint: extractHeaderHint(rawText),
  }));
}

// ---------------------------------------------------------------------------
// Ingest entry point
// ---------------------------------------------------------------------------

export function ingestReport(
  text: string,
  vendorHint: TimingVendor = "auto"
): IngestResult {
  const warnings: string[] = [];
  if (!text || !text.trim()) {
    return {
      kind: "unknown",
      vendor: "auto",
      detectedVendor: "synopsys",
      tool: "Unknown",
      stage: "unknown",
      rawBlocks: [],
      warnings: ["Empty report text provided."],
      isPs: false,
      headerLines: [],
      totalRawLines: 0,
    };
  }

  const detectedVendor = detectVendor(text);
  const effectiveVendor = vendorHint === "auto" ? detectedVendor : vendorHint;
  const tool = detectTool(text, effectiveVendor);

  let designName: string | undefined;
  let operatingConditions: string | undefined;
  let wireloadMode: string | undefined;
  let areaMode: string | undefined;

  const moduleMatch =
    text.match(/Module:\s*(\S+)/i) ||
    text.match(/Design\s*:\s*(\S+)/i) ||
    text.match(/Design\s+name\s*[:=]\s*(\S+)/i) ||
    text.match(/Block\s*[:=]\s*(\S+)/i) ||
    text.match(/Top\s*(?:module|cell)\s*[:=]\s*(\S+)/i);
  if (moduleMatch) designName = moduleMatch[1].trim().replace(/[,"']+$/g, "");

  const opMatch = text.match(/Operating conditions:\s*(.*)/i);
  if (opMatch) operatingConditions = opMatch[1].trim();

  const wlMatch = text.match(/Wireload mode:\s*(.*)/i);
  if (wlMatch) wireloadMode = wlMatch[1].trim();

  const areaMatch = text.match(/Area mode:\s*(.*)/i);
  if (areaMatch) areaMode = areaMatch[1].trim();

  const stage = detectFlowStage(tool, text, wireloadMode);
  const kind = detectReportKind(text);
  const isPs = detectIsPs(text);

  const lines = text.split("\n");
  const headerLines = lines.slice(0, 15).filter((l) => l.trim().startsWith("#") || l.includes(":") || l.includes("="));

  const rawBlocks = splitReportIntoBlocks(text, effectiveVendor);
  if (rawBlocks.length === 0) {
    warnings.push("No distinct timing path blocks found in report.");
  }

  return {
    kind,
    vendor: effectiveVendor,
    detectedVendor,
    tool,
    designName,
    operatingConditions,
    wireloadMode,
    areaMode,
    stage,
    rawBlocks,
    warnings,
    isPs,
    headerLines,
    totalRawLines: lines.length,
  };
}

// ---------------------------------------------------------------------------
// Multi-File Session Management
// ---------------------------------------------------------------------------

export function createReportSession(
  initialText?: string,
  filename = "report_1.rpt",
  vendorHint: TimingVendor = "auto"
): ReportSession {
  if (!initialText || !initialText.trim()) {
    return { files: [], activeId: "" };
  }
  const result = ingestReport(initialText, vendorHint);
  const file: IngestReportFile = {
    id: `file_${Date.now()}_1`,
    filename,
    text: initialText,
    parsedAt: Date.now(),
    result,
  };
  return {
    files: [file],
    activeId: file.id,
  };
}

export function addReportFile(
  session: ReportSession,
  filename: string,
  text: string,
  vendorHint: TimingVendor = "auto"
): ReportSession {
  const result = ingestReport(text, vendorHint);
  const file: IngestReportFile = {
    id: `file_${Date.now()}_${session.files.length + 1}`,
    filename,
    text,
    parsedAt: Date.now(),
    result,
  };
  return {
    files: [...session.files, file],
    activeId: file.id,
  };
}

export function switchActiveFile(
  session: ReportSession,
  fileId: string
): ReportSession {
  if (!session.files.some((f) => f.id === fileId)) return session;
  return {
    ...session,
    activeId: fileId,
  };
}

export function removeReportFile(
  session: ReportSession,
  fileId: string
): ReportSession {
  const files = session.files.filter((f) => f.id !== fileId);
  const activeId =
    session.activeId === fileId
      ? files.length > 0
        ? files[files.length - 1].id
        : ""
      : session.activeId;
  return { files, activeId };
}

export function getActiveFile(
  session: ReportSession
): IngestReportFile | undefined {
  return session.files.find((f) => f.id === session.activeId);
}
