import json

DOMAINS = [
    {
        "id": "lec_setup_mapping",
        "name": "Setup & Library Mapping",
        "tagline": "Golden/Revised netlist ingestion, blackbox modeling, standard cell Liberty models & pin constraints",
        "scenarios": [
            ("Missing Standard Cell Functional Liberty Definition in Revised Setup", "CRITICAL", "LEC Setup Mode",
             "Conformal LEC flags 1,240 library cells as unmapped blackboxes with unknown boolean truth tables.",
             "// Error: Cannot find functional model for cell 'AOI222_X4' in library\n// Warning: 1240 instances instantiated as primitive BLACKBOX\n// LEC-SETUP-014: Cannot proceed to compare mode with undefined library models",
             "Conformal requires complete transistor-level or functional Liberty/Verilog models loaded with read_library -both before elaboration.",
             "read_library -both -statetable -liberty /pdk/sky130/stdcells.lib\nelaborate_design -golden -root soc_top\nelaborate_design -revised -root soc_top",
             [("Blackbox Cells", "1,240"), ("Mapped Points", "0%")], [("Blackbox Cells", "0"), ("Mapped Points", "100%")],
             [("Read complete standard cell liberty models using read_library -both before elaborate_design", True, "Reading the liberty models with read_library -both resolves all cell definitions for both Golden and Revised netlists."),
              ("Set all unmodeled cells to ideal shorts", False, "Shorting cells creates illegal connections and corrupts boolean logic."),
              ("Delete the AOI222 cells from the netlist", False, "Deleting cells changes functional behavior."),
              ("Disable LEC library verification checks", False, "Without cell models, formal equivalence cannot be proven.")]),

            ("Analog Mixed-Signal (AMS) IP Blackbox Definition", "HIGH", "Design Elaboration",
             "Conformal fails to elaborate PLL and ADC macro blocks due to missing transistor schematics in digital netlists.",
             "// Error: Module 'pll_dpll_top' has no behavioral verilog definition in Golden netlist\n// LEC-ELAB-089: Unresolved module reference in top-level netlist",
             "Hard analog IPs, PLLs, and SerDes PHYs lacking synthesizable RTL must be explicitly declared as blackboxes using set_blackbox.",
             "set_blackbox pll_dpll_top -both\nset_blackbox adc_12b_macro -both\nelaborate_design -both",
             [("Elab Errors", "2"), ("Design State", "BLOCKED")], [("Elab Errors", "0"), ("Design State", "READY")],
             [("Declare hard analog macros as blackboxes using set_blackbox <module> -both", True, "Declaring analog IP as blackboxes treats their boundary pins as matching Key Points."),
              ("Replace PLL with a 1-bit wire", False, "Replacing PLL with a wire creates functional mismatch."),
              ("Synthesize the PLL from SPICE schematics", False, "Conformal does not simulate SPICE netlists."),
              ("Ignore pin connections to the ADC", False, "Ignoring pins breaks interface verification.")]),

            ("Scan Mode Pin Constraint Floating Failure", "CRITICAL", "Constraint Setup",
             "Post-scan netlist compares non-equivalent because scan_enable pin is floating, mixing shift logic with functional cones.",
             "// Compare Results: 4,820 NON-EQUIVALENT compare points\n// Root Cause: scan_enable input is unconstrained; evaluating under test shift mode",
             "In functional mode LEC, scan_enable and test_mode pins must be tied to 0 using add_pin_constraints to disable DFT shift paths.",
             "add_pin_constraints 0 scan_enable -both\nadd_pin_constraints 0 test_mode_i -both\nadd_pin_constraints 1 scan_rst_n -both\nset_system_mode lec\ncompare",
             [("Non-Equivalent", "4,820"), ("Equivalent", "0")], [("Non-Equivalent", "0"), ("Equivalent", "4,820")],
             [("Constrain test control pins to functional values using add_pin_constraints (scan_enable=0)", True, "Pin constraints ensure the formal engine evaluates only functional operational state space."),
              ("Remove scan flip-flops from the netlist", False, "Removing scan cells destroys the physical design netlist."),
              ("Set scan_enable to 1 during functional comparison", False, "Setting scan_enable to 1 forces the design into test shift mode."),
              ("Invert all scan chain outputs", False, "Inverting outputs corrupts logic.")]),

            ("Case Analysis Static Mode Pin Tie-Off", "HIGH", "Setup Mode",
             "Dual-protocol PCIe/SATA PHY netlist reports false non-equivalence because mode configuration pins are unconstrained.",
             "// Non-equivalent compare point: u_phy/mode_select_fsm\n// Golden evaluates PCIe protocol while Revised evaluates SATA protocol",
             "Static mode selector pins must be constrained with identical case values across Golden and Revised netlists.",
             "add_pin_constraints 1 pcie_mode_sel -both\nadd_pin_constraints 0 sata_mode_sel -both\nset_system_mode lec\ncompare",
             [("Mode Mismatches", "340"), ("Status", "FAIL")], [("Mode Mismatches", "0"), ("Status", "PASS")],
             [("Apply identical pin constraints with add_pin_constraints to lock mode configuration", True, "Locking mode pins ensures both netlists operate under the same protocol mode."),
              ("Compare PCIe against SATA simultaneously", False, "Different protocols are inherently non-equivalent."),
              ("Disconnect mode selection lines", False, "Disconnecting lines causes floating inputs."),
              ("Delete the SATA protocol logic from RTL", False, "Modifying RTL is incorrect when constraints solve the check.")]),

            ("SystemVerilog 2017 Interface Port Flattening Mismatch", "MEDIUM", "Elaboration",
             "Conformal fails to map AXI4 interface bundles between modular Golden RTL and flattened post-synthesis netlist.",
             "// Error: Port 'axi_if.awaddr' in Golden cannot be resolved in flattened Revised netlist\n// Mapping efficiency: 12% mapped",
             "SystemVerilog interface ports flatten with delimiter underscores; set_flatten_model ensures naming conventions align.",
             "set_naming_rule %s_%d -interface_bus -both\nset_flatten_model -seq_constant -gated_clock\nelaborate_design -both",
             [("Mapped Ports", "12%"), ("Unmapped", "480")], [("Mapped Ports", "100%"), ("Unmapped", "0")],
             [("Configure interface naming rules and flatten model with set_naming_rule and set_flatten_model", True, "Configuring naming rules maps SystemVerilog struct/interface ports to flattened wire names."),
              ("Convert all interfaces to 1-bit ports manually in RTL", False, "Manual RTL refactoring is tedious and error-prone."),
              ("Disable interface checking in LEC", False, "Interface ports must be verified."),
              ("Remove AXI bus from Golden RTL", False, "Removing the bus breaks functionality.")]),

            ("Multi-Voltage UPF Power State Table (PST) Definition Missing", "CRITICAL", "Low Power Setup",
             "Power-gated domain registers evaluate to unknown 'X' in Revised netlist because power switch state is undefined.",
             "// Warning: Power switch 'u_sw_cpu' in Revised has no valid ON condition\n// Compare: 1,840 compare points evaluate to 'X' (Unknown)",
             "When comparing low-power netlists, load UPF power intent with read_power_intent to define active power supply states.",
             "read_power_intent -both ./upf/soc_power.upf\nset_power_state -domain PD_CPU -state ON\nset_system_mode lec\ncompare",
             [("X-State Points", "1,840"), ("Equivalence", "UNKNOWN")], [("X-State Points", "0"), ("Equivalence", "EQUIVALENT")],
             [("Read UPF power intent using read_power_intent and set active power states", True, "Loading UPF intent models power switches, level shifters, and isolation states properly."),
              ("Force all power-gated registers to 0", False, "Forcing values masks functional bugs."),
              ("Delete the power domain from UPF", False, "Deleting power intent defeats low-power verification."),
              ("Bypass UPF verification during LEC", False, "UPF power gating logic must be proven formally.")]),

            ("Floating Net Modeling & High-Z Resolution", "LOW", "Elaboration",
             "Unconnected internal test pins in Revised netlist generate false non-equivalent compare points.",
             "// Warning: Net 'u_core/test_spare_n' is floating in Revised design\n// Conformal models floating nets as non-deterministic free variables",
             "Floating nets should be tied to 0 or treated as don't-care using set_undriven_signal.",
             "set_undriven_signal 0 -both\nset_system_mode lec\ncompare",
             [("False Violations", "45"), ("Status", "FAIL")], [("False Violations", "0"), ("Status", "PASS")],
             [("Set undriven signal resolution to 0 using set_undriven_signal 0 -both", True, "Modeling undriven nets as tied-low matches physical synthesis tie-off behavior."),
              ("Connect floating pins to the clock tree", False, "Connecting floating signals to clock creates massive glitches."),
              ("Delete all undriven instances", False, "Arbitrary deletion corrupts physical netlists."),
              ("Set undriven signals to oscillate", False, "Oscillation causes simulation divergence.")]),

            ("Hierarchy Inversion in Sub-Block Netlists", "HIGH", "Elaboration",
             "Conformal cannot match internal hierarchy because Innovus flattened logic inside sub-modules during P&R.",
             "// Error: Module 'u_crypto/aes_round_stage' missing in Revised netlist\n// Mapping failure: Hierarchical boundaries altered during physical optimization",
             "When sub-blocks are ungrouped during synthesis/PnR, flatten the verification model with set_flatten_model.",
             "set_flatten_model -gated_clock -seq_constant\nmap_key_points -all\nset_system_mode lec\ncompare",
             [("Unmapped Modules", "8"), ("Mapped Points", "45%")], [("Unmapped Modules", "0"), ("Mapped Points", "100%")],
             [("Enable automatic model flattening using set_flatten_model", True, "Flattening the model resolves cross-module boundary optimizations and ungrouped logic."),
              ("Re-instantiate original sub-modules manually", False, "Manual netlist editing violates signoff integrity."),
              ("Disable hierarchical checking entirely", False, "Flattens without checking causes false passes."),
              ("Force all sub-modules to preserve boundaries during synthesis", False, "Boundary preservation degrades PnR PPA.")]),

            ("Constant Bit-Width Truncation Warning", "MEDIUM", "Elaboration",
             "32-bit adder in Golden RTL connected to 24-bit bus causes unmapped dangling MSB bits.",
             "// Warning: Bits [31:24] of adder output are unused in Golden design\n// Revised netlist pruned MSB logic gates during synthesis optimization",
             "Unconnected or pruned register bits must be analyzed as constant don't-cares using set_analyze_option -auto.",
             "set_analyze_option -auto -constant_propagation\nmap_key_points\nset_system_mode lec\ncompare",
             [("Dangling Bits", "8"), ("Status", "WARNING")], [("Dangling Bits", "0"), ("Status", "CLEAN")],
             [("Enable constant propagation and automatic dead logic pruning with set_analyze_option", True, "Auto analysis identifies unused bits pruned identically in synthesis."),
              ("Pad Revised netlist with 8 dummy flip-flops", False, "Adding dummy flops alters physical design."),
              ("Short the MSB bits to ground in RTL", False, "Modifying RTL is unnecessary when tool analyzes pruning."),
              ("Disable unused port warnings in LEC", False, "Disabling warnings can mask real truncation bugs.")]),

            ("SDC Case Analysis Direct Propagation", "HIGH", "Setup Mode",
             "BIST and Functional modes conflict on shared test muxes without SDC case constants.",
             "// Compare: 920 points non-equivalent on MBIST test control cones\n// Mismatch: Test mux output evaluated in both 0 and 1 states simultaneously",
             "Ingest SDC constraints with read_sdc to propagate set_case_analysis constants to formal compare points.",
             "read_sdc -both ./constraints/functional_signoff.sdc\nset_system_mode lec\ncompare",
             [("Conflicting Muxes", "920"), ("Status", "FAIL")], [("Conflicting Muxes", "0"), ("Status", "PASS")],
             [("Load functional SDC constraints using read_sdc -both to apply case analysis constants", True, "Loading SDC propagates set_case_analysis mode settings across test muxes."),
              ("Hard-wire all mux select pins to 0 in Verilog", False, "Hard-wiring in Verilog corrupts test mode silicon."),
              ("Delete the MBIST controllers from netlist", False, "Deleting MBIST destroys manufacturing test."),
              ("Ignore test mux compare points", False, "Ignoring compare points creates verification holes.")])
        ]
    },
    {
        "id": "lec_keypoint_mapping",
        "name": "Key Point Mapping & Unmapped Resolution",
        "tagline": "Register renaming heuristics, state machine re-encoding, phase inversion & MBFF mapping",
        "scenarios": [
            ("Phase-Inverted Register Mapping Failure", "CRITICAL", "Key Point Mapping",
             "Synthesis inverted an active-low reset register into an active-high equivalent with inverted data polarity, causing unmapped points.",
             "// Unmapped Points: 64 Non-equivalent DFFs in u_dma/ctrl_reg[*]\n// Warning: Inverted Q pin polarity detected on Revised register",
             "When synthesis inverts register phase to save silicon area, enable phase inversion mapping with set_mapping_method -invert.",
             "set_mapping_method -invert\nmap_key_points\nset_system_mode lec\ncompare",
             [("Unmapped DFFs", "64"), ("Equivalence", "FAIL")], [("Unmapped DFFs", "0"), ("Equivalence", "PASS")],
             [("Enable phase-inverted register mapping using set_mapping_method -invert", True, "Phase inversion mapping recognizes registers with inverted reset polarity and inverted output cones."),
              ("Invert the clock signal in the Revised netlist", False, "Inverting clock breaks sequential timing and functional behavior."),
              ("Insert an inverter on each DFF output in RTL", False, "RTL modifications are unnecessary for synthesis optimizations."),
              ("Force synthesis to disable area optimization", False, "Disabling optimization degrades area and power.")]),

            ("Multi-Bit Flip-Flop (MBFF) Decomposition Mapping", "HIGH", "Key Point Mapping",
             "Innovus merged four 1-bit registers into a single 4-bit MBFF (DFF_X4_MBFF), resulting in unmapped 1-bit Golden names.",
             "// Unmapped Golden: u_pipe/reg_a_0_reg, reg_a_1_reg, reg_a_2_reg, reg_a_3_reg\n// Unmapped Revised: u_pipe/reg_a_mbff4_reg[3:0]",
             "Multi-Bit Flip-Flop merging groups bit slices under a single cell; Conformal maps individual bit pins using name rule heuristics.",
             "set_naming_rule -mbff \"%s_mbff%d_reg[%d]\" -revised\nmap_key_points -mbff\nset_system_mode lec\ncompare",
             [("Unmapped MBFFs", "256"), ("Mapping Rate", "74%")], [("Unmapped MBFFs", "0"), ("Mapping Rate", "100%")],
             [("Configure MBFF naming heuristics and map with map_key_points -mbff", True, "MBFF mapping decomposes multi-bit register pins into individual Golden 1-bit compare points."),
              ("Split all MBFFs back into 1-bit cells in PnR netlist", False, "Splitting MBFFs destroys 25% clock power savings."),
              ("Ignore MBFF register compare points", False, "Ignoring registers invalidates formal equivalence."),
              ("Treat MBFF cells as blackboxes", False, "Treating registers as blackboxes skips pipeline checks.")]),

            ("FSM State Machine Re-Encoding (One-Hot to Binary)", "CRITICAL", "Key Point Mapping",
             "Synthesis re-encoded an 8-state One-Hot FSM into a 3-bit Binary counter, causing 5 unmapped Golden registers.",
             "// Unmapped Golden: u_fsm/state_reg[7:3] (One-Hot 8 FFs)\n// Revised: u_fsm/state_reg[2:0] (Binary 3 FFs)\n// LEC-MAP-042: Mismatched sequential state encoding",
             "Sequential FSM re-encoding alters state register count; read the synthesis SVF/FV_MAP record or use sequential comparison.",
             "read_fv_map -fsm ./synthesis/fsm_encoding.map\nset_system_mode lec\nadd_compared_points -all\ncompare",
             [("Unmapped State FFs", "5"), ("Status", "ABORT")], [("Unmapped State FFs", "0"), ("Status", "EQUIVALENT")],
             [("Ingest synthesis formal verification map using read_fv_map for FSM re-encoding", True, "The FV map guides Conformal through state variable transformations."),
              ("Force RTL to use 3-bit binary encoding manually", False, "Manual RTL edits risk introducing functional errors."),
              ("Delete the 5 unmapped registers from Golden RTL", False, "Deleting registers breaks RTL simulation."),
              ("Disable FSM comparison in Conformal", False, "FSM verification is critical for chip control logic.")]),

            ("Sequential Retiming Pipeline Register Shift", "HIGH", "Key Point Mapping",
             "Genus moved pipeline registers across a 32-bit multiplier cone (retime_design), breaking 1-to-1 register mapping.",
             "// Non-equivalent compare points: 32 DFFs moved across multiplier\n// Golden has 1 pre-mult register; Revised has 2 post-mult registers",
             "Sequential retiming shifts registers across logic gates; load the retiming guide record via read_fv_map.",
             "read_fv_map -retime ./synthesis/genus_retiming.map\nset_system_mode lec\ncompare",
             [("Retimed Non-Equiv", "32"), ("Proof", "FAIL")], [("Retimed Non-Equiv", "0"), ("Proof", "PASS")],
             [("Ingest the synthesis retiming guidebook using read_fv_map -retime", True, "The retiming map allows Conformal to verify sequential equivalence across shifted register boundaries."),
              ("Disable retiming in Genus synthesis", False, "Disabling retiming degrades maximum operating frequency."),
              ("Insert delay cells in Golden RTL", False, "Delay cells cannot be modeled in cycle-accurate RTL."),
              ("Ignore multiplier pipeline registers", False, "Ignoring registers creates functional escape bugs.")]),

            ("Register Merging on Identical Fanin Cones", "MEDIUM", "Key Point Mapping",
             "Synthesis merged two redundant status registers driving identical logic cones into a single register with two fanout branches.",
             "// Unmapped Golden: u_ctrl/status_err_reg_dup\n// Revised has single instance: u_ctrl/status_err_reg",
             "Redundant register merging reduces gate count; Conformal resolves merged registers using set_flatten_model -seq_constant.",
             "set_flatten_model -seq_constant -gated_clock\nmap_key_points\nset_system_mode lec\ncompare",
             [("Unmapped Duplicates", "18"), ("Equivalence", "INCOMPLETE")], [("Unmapped Duplicates", "0"), ("Equivalence", "EQUIVALENT")],
             [("Enable sequential constant and equivalent register merging analysis with set_flatten_model", True, "Setting seq_constant models redundant register pruning formally."),
              ("Prohibit register merging in synthesis scripts", False, "Prohibiting merging wastes flip-flop area and clock power."),
              ("Replicate the register manually in Revised netlist", False, "Manual netlist hacking risks DRC and timing violations."),
              ("Set duplicate registers to don't-care", False, "Setting registers to don't-care bypasses verification.")]),

            ("Clock Tree Synthesis Root Buffer Key Point Shift", "LOW", "Post-CTS Mapping",
             "Post-route netlist clock pins are driven by CTS buffer trees (CLKBUF_X12) instead of primary clock ports.",
             "// Info: Clock ports in Revised netlist drive 4-level CTS buffer trees\n// Mapping primary clock ports to internal leaf pins",
             "CTS inserts buffer trees; Conformal automatically traces clock pins back to root ports unless unmapped.",
             "set_mapping_method -clock_tree\nmap_key_points\nset_system_mode lec\ncompare",
             [("Clock Pin Mismatches", "42"), ("Status", "WARN")], [("Clock Pin Mismatches", "0"), ("Status", "CLEAN")],
             [("Enable clock tree buffer tracing using set_mapping_method -clock_tree", True, "Clock tree mapping traces clock buffers back to primary clock sources."),
              ("Delete all clock buffers from PnR netlist", False, "Deleting clock buffers destroys clock distribution."),
              ("Add inverters on all clock lines", False, "Adding inverters inverts clock edges."),
              ("Ignore clock pin connections", False, "Clock pins must be validated.")]),

            ("Constant 0/1 Tied-Off Register Pruning", "MEDIUM", "Key Point Mapping",
             "Synthesis pruned 16 configuration registers whose D-inputs were tied to constant 0 during synthesis optimization.",
             "// Unmapped Golden: u_cfg/feature_en_reg[15:0]\n// Revised netlist tied downstream logic directly to VSS",
             "Registers tied to constants are eliminated during optimization; Conformal matches them to constant 0/1 compare points.",
             "set_flatten_model -seq_constant\nmap_key_points\nset_system_mode lec\ncompare",
             [("Tied-Off Unmapped", "16"), ("Status", "FAIL")], [("Tied-Off Unmapped", "0"), ("Status", "PASS")],
             [("Enable constant sequential folding with set_flatten_model -seq_constant", True, "Constant sequential folding proves logic driven by constant registers matches tied-off nets."),
              ("Force RTL to remove the constant registers", False, "RTL may keep configuration registers for future expansion."),
              ("Instantiate 16 dummy registers tied to VDD", False, "Tying to VDD inverts constant 0 logic."),
              ("Disable constant propagation in synthesis", False, "Disabling constant propagation wastes silicon area.")]),

            ("Shift Register LUT (SRL) RAM Inference Mapping", "HIGH", "Key Point Mapping",
             "Synthesis mapped a 32-stage FIFO shift register into an SRAM macro cell, leaving 32 discrete flip-flops unmapped in Golden.",
             "// Unmapped Golden: u_fifo/sr_reg[31:0]\n// Revised has single RAM instance: u_fifo/srl_mem_32x8",
             "Memory macro inference changes register primitives into RAM arrays; blackbox the RAM or load behavioral RAM models.",
             "read_library -both ./models/srl_mem_model.v\nset_flatten_model -seq_constant\nmap_key_points\nset_system_mode lec\ncompare",
             [("Unmapped DFFs", "32"), ("RAM Mapped", "NO")], [("Unmapped DFFs", "0"), ("RAM Mapped", "YES")],
             [("Provide behavioral simulation models for inferred RAM macros with read_library", True, "Behavioral models allow Conformal to verify functional equivalence of memory arrays."),
              ("Force synthesis to use discrete flip-flops only", False, "Using discrete flops increases area by 4x."),
              ("Short RAM input pins directly to outputs", False, "Shorting pins eliminates FIFO delay storage."),
              ("Delete the FIFO from verification scope", False, "Deleting the FIFO introduces critical verification gaps.")]),

            ("Name Mangling Across Verilog Hierarchy Flattening", "MEDIUM", "Key Point Mapping",
             "Synthesis replaced hierarchy forward slashes '/' with underscores '__', causing 2,400 unmapped name mismatches.",
             "// Golden Name: u_top/u_alu/res_reg[0]\n// Revised Name: u_top__u_alu__res_reg_0_\n// Mapping Rate: 8%",
             "Hierarchy flattening character substitutions must be defined using set_naming_rule to match bus brackets and delimiters.",
             "set_naming_rule -hier_delimiter \"__\" -bus_delimiter \"_%d_\" -revised\nmap_key_points\nset_system_mode lec\ncompare",
             [("Unmapped Names", "2,400"), ("Mapped Rate", "8%")], [("Unmapped Names", "0"), ("Mapped Rate", "100%")],
             [("Configure hierarchy and bus delimiter rules using set_naming_rule", True, "Setting delimiter rules bridges naming differences between hierarchical RTL and flattened netlists."),
              ("Rename all instances in the netlist manually with sed", False, "Manual sed renaming is error-prone and brittle."),
              ("Preserve all hierarchy during synthesis", False, "Preserving all hierarchy hinders boundary logic optimization."),
              ("Disable name-based mapping heuristics", False, "Disabling heuristics prevents automatic Key Point matching.")]),

            ("Latch-Based Time-Borrowing Pipeline Key Point Resolution", "HIGH", "Key Point Mapping",
             "Transparent latch array in high-speed datapath generates feedback loop warnings and unmapped latch compare points.",
             "// Warning: Combinational feedback loop detected through transparent latch array\n// Unmapped Compare Points: 16 Latches in u_datapath/latch_bank[*]",
             "Transparent latches require phase modeling; enable latch mapping using set_flatten_model -latch.",
             "set_flatten_model -latch -loop_break\nmap_key_points\nset_system_mode lec\ncompare",
             [("Feedback Loops", "16"), ("Latch Points", "UNMAPPED")], [("Feedback Loops", "0"), ("Latch Points", "MAPPED")],
             [("Enable latch loop breaking and latch mapping with set_flatten_model -latch", True, "Setting latch mode allows Conformal to break transparent loops and verify latch stages cleanly."),
              ("Replace all latches with edge-triggered flip-flops in RTL", False, "Replacing latches removes time-borrowing performance margins."),
              ("Short latch D-pins to Q-pins directly", False, "Shorting pins removes sequential isolation."),
              ("Ignore latch feedback loops", False, "Ignoring feedback loops leads to non-convergent analysis.")])
        ]
    },
    {
        "id": "lec_datapath_arithmetic",
        "name": "Datapath & Arithmetic Optimization",
        "tagline": "Carry-Save Adder (CSA) restructuring, Booth multiplier re-architecting & BDD datapath solvers",
        "scenarios": [
            ("Booth-Wallace 64-bit Multiplier Restructuring Equivalence", "CRITICAL", "Datapath Solver",
             "Conformal BDD engine times out on a 64-bit Booth-encoded multiplier restructured into Wallace tree reduction.",
             "// Warning: Compare point u_dsp/mult_64b timed out after 3600s\n// State: Non-convergent in default BDD solver",
             "Complex non-linear datapath architectures require Conformal's dedicated Word-Level and Arithmetic solvers enabled via set_compare_options -threads.",
             "set_analyze_option -datapath -word_level\nset_compare_options -threads 8\ncompare",
             [("BDD Timeout", "3600s"), ("Verification", "INCONCLUSIVE")], [("BDD Timeout", "12s"), ("Verification", "EQUIVALENT")],
             [("Enable word-level arithmetic and datapath solver engines with set_analyze_option -datapath", True, "Word-level solvers use algebraic rewriting to prove multiplier equivalence in seconds."),
              ("Replace the 64-bit multiplier with a lookup table", False, "LUTs for 64-bit multipliers require exabytes of memory."),
              ("Reduce multiplier bit-width to 4 bits", False, "Reducing bit-width invalidates full 64-bit arithmetic proof."),
              ("Bypass arithmetic blocks during LEC signoff", False, "Bypassing datapath hides catastrophic silicon calculation errors.")]),

            ("Carry-Save Adder (CSA) Tree Bit-Slice Swizzling", "HIGH", "Datapath Solver",
             "Synthesis reordered sum and carry vector accumulation order across 8 operand inputs, failing bit-level compare.",
             "// Non-equivalent compare points: u_alu/csa_tree_sum[63:0]\n// Mismatch: Partial product summation order re-ordered during synthesis",
             "Carry-save addition is associative and commutative; datapath analysis solves algebraic polynomial equivalence.",
             "set_analyze_option -auto -datapath\nadd_compared_points -all\ncompare",
             [("CSA Non-Equiv", "64"), ("Status", "FAIL")], [("CSA Non-Equiv", "0"), ("Status", "PASS")],
             [("Enable automatic datapath associative equivalence using set_analyze_option -datapath", True, "Datapath analysis proves algebraic sum equivalence regardless of tree restructuring."),
              ("Force synthesis to use linear ripple-carry adders", False, "Ripple-carry adders violate high-performance timing budgets."),
              ("Invert the carry bits manually in netlist", False, "Inverting carry bits produces wrong arithmetic answers."),
              ("Delete the CSA accumulator tree", False, "Deleting the accumulator breaks ALU function.")]),

            ("Resource Sharing Arithmetic Operator Multiplexing", "MEDIUM", "Datapath Solver",
             "Synthesis merged two distinct 32-bit adders from an if-else RTL construct into a single shared adder with input multiplexers.",
             "// Unmapped Golden: u_core/adder_branch_a, adder_branch_b\n// Revised: u_core/shared_adder_inst",
             "Resource sharing preserves input-output transfer function; Conformal proves equivalence across condition branches.",
             "set_flatten_model -seq_constant\nset_analyze_option -datapath\ncompare",
             [("Unmapped Adders", "2"), ("Equivalence", "UNVERIFIED")], [("Unmapped Adders", "0"), ("Equivalence", "EQUIVALENT")],
             [("Enable datapath condition branch analysis with set_analyze_option -datapath", True, "Datapath analysis proves shared arithmetic units match independent RTL branches."),
              ("Disable resource sharing in synthesis", False, "Disabling sharing inflates standard cell area by 30%."),
              ("Duplicate the adder in Revised netlist", False, "Duplicating adders wastes area and breaks PnR."),
              ("Tie branch condition inputs to constant 1", False, "Tying conditions tests only one branch.")]),

            ("Leading Zero Anticipator (LZA) Floating Point Equivalence", "HIGH", "Datapath Solver",
             "Custom LZA logic in floating-point unit uses speculative prediction bits that differ from behavioral RTL counting loops.",
             "// Non-equivalent compare points: u_fpu/lza_norm_shift[5:0]\n// Counter-example vector: mantissa = 0x0000_8000_0000_0000",
             "LZA algorithms compute leading zeros concurrently with subtraction; algebraic solvers verify bitwise truth tables.",
             "set_analyze_option -datapath -fpu\ncompare",
             [("LZA Non-Equiv", "6"), ("Status", "FAIL")], [("LZA Non-Equiv", "0"), ("Status", "PASS")],
             [("Enable FPU and datapath normalization solver with set_analyze_option -fpu", True, "FPU solver options handle speculative leading zero detection equivalence."),
              ("Rewrite RTL to use standard gate-level LZA code", False, "Behavioral RTL should remain clean and portable."),
              ("Disable normalization checks", False, "Normalization is essential for IEEE 754 precision."),
              ("Force mantissa shift to constant 0", False, "Forcing shift corrupts floating-point results.")]),

            ("Saturating Arithmetic Overflow Clamping Verification", "MEDIUM", "Datapath Solver",
             "DSP saturating accumulator netlist implements carry-lookahead clamping logic optimized with compound gates.",
             "// Compare: 32 Points in u_dsp/sat_accum_reg[*]\n// Result: EQUIVALENT (Proven in 0.8s via Arithmetic Engine)",
             "Compound gate mapping preserves saturation boundary clamps at maximum positive (0x7FFF) and negative (0x8000) bounds.",
             "add_compared_points u_dsp/sat_accum_reg[*]\ncompare",
             [("Compare Points", "32"), ("Status", "READY")], [("Compare Points", "32"), ("Status", "EQUIVALENT")],
             [("Add saturating register compare points and execute datapath compare", True, "Conformal verifies overflow clamp logic equivalence formally across all 2^32 input states."),
              ("Disable saturation clamping during synthesis", False, "Disabling saturation produces rollover audio distortion."),
              ("Add external clamping buffers in PnR", False, "Clamping logic belongs in the synthesized netlist."),
              ("Set saturation flags to don't-care", False, "Flags must be verified for architecture compliance.")]),

            ("Polynomial CRC-32 Generator Matrix Factoring", "HIGH", "Datapath Solver",
             "Synthesis factored an iterative CRC-32 LFSR into a parallel 64-bit XOR parity tree matrix.",
             "// Non-equivalent compare points: u_eth/crc_out[31:0]\n// Complex multi-level XOR parity tree mismatch",
             "Linear XOR trees can be simplified using Conformal's linear solver (set_analyze_option -linear).",
             "set_analyze_option -linear\ncompare",
             [("CRC Non-Equiv", "32"), ("Status", "FAIL")], [("CRC Non-Equiv", "0"), ("Status", "PASS")],
             [("Activate linear XOR parity solver with set_analyze_option -linear", True, "The linear solver applies Galois field GF(2) matrix reduction to prove parallel CRC equivalence."),
              ("Force synthesis to keep serial LFSR structure", False, "Serial LFSR cannot achieve 100 Gbps Ethernet throughput."),
              ("Short CRC parity outputs together", False, "Shorting outputs breaks CRC error detection."),
              ("Delete the CRC module from verification", False, "Ethernet frames cannot pass without valid CRC.")]),

            ("Restoring Non-Linear Division Array Optimization", "CRITICAL", "Datapath Solver",
             "Radix-4 SRT division array in hardware math coprocessor timed out under standard BDD representation.",
             "// Warning: Division compare points non-convergent after 1800s\n// Memory utilization: 14.2 GB",
             "Non-linear division algorithms require SAT-based algebraic solvers with incremental bound checking.",
             "set_compare_options -solver sat -timeout 300\nset_analyze_option -datapath\ncompare",
             [("Solver State", "TIMEOUT"), ("Memory", "14.2 GB")], [("Solver State", "EQUIVALENT"), ("Memory", "2.1 GB")],
             [("Switch to SAT-based datapath solver with set_compare_options -solver sat", True, "SAT solvers avoid BDD memory explosion on non-linear division arrays."),
              ("Replace hardware divider with software emulation", False, "Hardware division is required for compute throughput."),
              ("Reduce division dividend to 8 bits", False, "Trimming dividend width fails full 64-bit verification."),
              ("Ignore division remainder registers", False, "Remainder registers must be verified.")]),

            ("Constant Factor Arithmetic Strength Reduction", "LOW", "Datapath Solver",
             "Synthesis replaced multiplication by constant 10 (`x * 10`) with shifts and adds (`(x << 3) + (x << 1)`).",
             "// Compare: u_algo/scale_out[15:0]\n// Result: EQUIVALENT (Proven in 0.2s)",
             "Strength reduction transforms expensive multipliers into wire shifts and adders with exact mathematical equivalence.",
             "add_compared_points u_algo/scale_out[*]\ncompare",
             [("Multipliers", "1"), ("Adders", "1")], [("Multipliers", "0"), ("Adders", "1")],
             [("Execute compare on strength-reduced shift-add logic", True, "Conformal's arithmetic solver verifies shift-add expansion matches constant multiplication perfectly."),
              ("Force synthesis to use hardware DSP multiplier", False, "Using DSP blocks for constant 10 wastes silicon area."),
              ("Add division by 10 to reverse the math", False, "Division introduces truncation errors."),
              ("Disable strength reduction optimization", False, "Disabling strength reduction hurts power and area.")]),

            ("Bit-Slice Swizzling & Endianness Invariance", "MEDIUM", "Datapath Solver",
             "Big-endian to little-endian byte swapper in network packet parser failed initial wire naming match.",
             "// Golden: packet_data[31:0] -> {byte3, byte2, byte1, byte0}\n// Revised: packet_data_rev[31:0] mapped with reversed slice indices",
             "Byte swizzling is a pure wiring transposition; Conformal resolves wiring maps under set_flatten_model.",
             "set_flatten_model -seq_constant\nmap_key_points -name_rule\ncompare",
             [("Unmapped Slices", "4"), ("Equivalence", "FAIL")], [("Unmapped Slices", "0"), ("Equivalence", "PASS")],
             [("Map wire transposition using set_flatten_model and map_key_points -name_rule", True, "Name rule matching resolves bit-slice endianness transformations without logic changes."),
              ("Invert all byte registers in Verilog", False, "Inverting registers corrupts packet payload."),
              ("Force network parser to use 8-bit bus", False, "8-bit bus reduces throughput by 4x."),
              ("Delete byte swap logic from RTL", False, "Byte swapping is mandatory for network protocol interop.")]),

            ("Modulo Arithmetic Sign-Extension Optimization", "LOW", "Datapath Solver",
             "Two's complement sign extension on 16-to-32 bit signed accumulator matched seamlessly under formal algebra.",
             "// Compare: u_dsp/acc_32b[31:0]\n// Result: EQUIVALENT (Proven in 0.1s)",
             "Sign extension replicates MSB across higher order bits; Conformal proves boolean invariance across all 65,536 input states.",
             "compare",
             [("Compare Points", "32"), ("Status", "VERIFIED")], [("Compare Points", "32"), ("Status", "EQUIVALENT")],
             [("Run standard compare on sign-extended accumulator", True, "Conformal verifies two's complement sign-extension logic automatically."),
              ("Zero-pad the signed inputs instead", False, "Zero padding converts signed numbers to positive unsigned."),
              ("Insert an inverter on MSB bit", False, "Inverting MSB inverts number sign incorrectly."),
              ("Disable two's complement arithmetic in RTL", False, "Two's complement is fundamental to digital DSP.")])
        ]
    },
    {
        "id": "lec_low_power_upf",
        "name": "Low-Power UPF & Power Gating",
        "tagline": "Isolation cells, level shifters, retention latches (SRPG) & power switch formal proofs",
        "scenarios": [
            ("Missing Low-to-High Level Shifter Cell on Cross-Domain Signal", "CRITICAL", "Low Power LEC",
             "Conformal UPF verification catches a missing level shifter cell between 0.65V CPU core and 0.95V peripheral bus.",
             "// Error: Voltage domain crossing from 0.65V (PD_CORE) to 0.95V (PD_SOC) lacks level shifter\n// Violation: UPF rule 'LS_CORE_TO_SOC' violated on net 'u_core/intr_ack'",
             "Low-to-high voltage crossings require level shifter cells (LS_L2H) to prevent PMOS crowbar current and voltage mismatch.",
             "read_power_intent -both ./upf/soc_power.upf\nset_power_state -both\nverify_power_intent\ncompare",
             [("Missing Level Shifters", "1"), ("UPF Violations", "1")], [("Missing Level Shifters", "0"), ("UPF Violations", "0")],
             [("Verify UPF power intent using verify_power_intent to flag missing level shifter insertion", True, "Formal power intent verification proves all cross-voltage nets have verified level shifter cells."),
              ("Remove the 0.65V power domain to match 0.95V", False, "Removing domain defeats low-power battery optimization."),
              ("Short 0.65V and 0.95V supplies together", False, "Shorting supplies destroys the chip with over-voltage."),
              ("Disable level shifter verification in Conformal", False, "Disabling checks causes silicon crowbar failure.")]),

            ("Isolation Cell Clamp State Polarity Inversion (0 vs 1)", "CRITICAL", "Low Power LEC",
             "Active-low reset signal (`rst_n`) was clamped to 0 instead of 1 during power-down mode, causing perpetual reset upon wake-up.",
             "// Non-equivalent compare point: u_periph/rst_n (Isolation Clamp)\n// Golden UPF specifies clamp_value 1; Revised netlist implements ISO_AND (clamp 0)",
             "Active-low control nets must use OR-type isolation cells clamped to 1 so receiving active logic is not asserted during sleep.",
             "// Remedy: Update UPF isolation rule to clamp active-low signals to 1\nset_isolation iso_rst -domain PD_CPU -clamp_value 1 -elements {u_core/rst_n}\nverify_power_intent",
             [("Clamp Value", "0 (Illegal)"), ("Wakeup State", "DEADLOCK")], [("Clamp Value", "1 (Clean)"), ("Wakeup State", "NORMAL")],
             [("Enforce clamp_value 1 on active-low reset isolation rules in UPF", True, "Clamping active-low nets to 1 prevents false reset assertion during domain sleep mode."),
              ("Invert the reset pin inside active peripheral domain", False, "Inverting pin in active domain breaks normal reset operation."),
              ("Delete isolation cells on reset signals", False, "Deleting isolation allows floating mid-rail voltage to crash active logic."),
              ("Tie the reset line permanently to ground", False, "Tying reset to ground keeps the chip in perpetual reset.")]),

            ("State Retention Power Gating (SRPG) Shadow Latch Proof", "HIGH", "Low Power LEC",
             "State retention registers in power-gated CPU core failed equivalence because save/restore control pins were swapped.",
             "// Non-equivalent compare points: 1,024 Retention Registers in PD_CPU\n// Mismatch: Save signal mapped to RESTORE pin on RET_DFF cells",
             "Retention registers contain dedicated shadow latches; Conformal verifies save/restore state transfer functions formally.",
             "verify_power_intent -retention\nset_system_mode lec\ncompare",
             [("Retention Errors", "1,024"), ("State Recovery", "FAIL")], [("Retention Errors", "0"), ("State Recovery", "PASS")],
             [("Run verify_power_intent -retention to formalize save/restore pin mapping on SRPG cells", True, "Formal retention checks prove register states save before power-down and restore cleanly upon wake-up."),
              ("Replace retention registers with normal flip-flops", False, "Normal flops lose architectural state during sleep."),
              ("Keep the CPU core permanently powered on", False, "Defeats standby sleep power targets."),
              ("Disable retention verification in Conformal", False, "Skipping retention checks leads to sleep/wake crashes.")]),

            ("Always-On (AON) Clock Buffer Power Net Connectivity", "HIGH", "Low Power LEC",
             "Always-on clock buffer routing through power-gated region was inadvertently connected to switched virtual VDD.",
             "// Error: Instance 'u_cts/aon_clk_buf_4' inside switched domain PD_GPU connected to VDD_VIRTUAL\n// Rule: Always-on cells must connect to permanent VDD_AON",
             "Always-on buffers crossing sleeping domains must have their primary power pins connected to continuous VDD_AON.",
             "verify_power_intent -always_on\ncompare",
             [("AON Power Violations", "12"), ("Clock in Sleep", "DEAD")], [("AON Power Violations", "0"), ("Clock in Sleep", "ACTIVE")],
             [("Execute verify_power_intent -always_on to certify permanent VDD_AON power connections", True, "AON verification ensures clock buffers stay alive even when surrounding domain is powered down."),
              ("Convert all clock buffers to switched power", False, "Switched buffers freeze clocks across active domains."),
              ("Short virtual VDD to permanent VDD", False, "Shorting power rails defeats power gating."),
              ("Delete always-on buffers from CTS", False, "Deleting buffers causes clock skew failures.")]),

            ("Power Switch Enable Daisy-Chain Invariance Proof", "MEDIUM", "Low Power LEC",
             "Synthesized netlist daisy-chained 400 MTCMOS header switches, altering control net structure without changing boolean state.",
             "// Compare: u_power/sw_ctrl_chain[*]\n// Result: EQUIVALENT (Proven switch control logic matches UPF intent)",
             "Power switch daisy-chains staggered for inrush current control do not alter the steady-state functional boolean domain.",
             "verify_power_intent -power_switch\ncompare",
             [("Power Switches", "400"), ("Status", "UNCHECKED")], [("Power Switches", "400"), ("Status", "VERIFIED")],
             [("Verify power switch network integrity using verify_power_intent -power_switch", True, "Power switch formal checks confirm sleep enable signals reach all MTCMOS switches cleanly."),
              ("Remove MTCMOS power switches from netlist", False, "Removing switches prevents domain power shutoff."),
              ("Short all switch gates to permanent ground", False, "Shorting gates turns switches permanently on."),
              ("Invert sleep enable polarity in RTL", False, "Inverting polarity keeps switches off during active mode.")]),

            ("DVFS Multi-Voltage Operating State Equivalence", "HIGH", "Low Power LEC",
             "SoC operating at 0.55V Super-Low-Power and 0.85V Turbo-Performance verified identical across logic functions.",
             "// Compare: All 45,000 Compare Points across DVFS States\n// Result: EQUIVALENT (DVFS modes do not alter boolean logic)",
             "Dynamic Voltage and Frequency Scaling alters operational voltage and delay without modifying digital boolean truth tables.",
             "set_power_state -state {LOW_V TURBO_V}\ncompare",
             [("DVFS States", "2"), ("Equivalence", "READY")], [("DVFS States", "2"), ("Equivalence", "EQUIVALENT")],
             [("Run multi-state power verification across all defined DVFS operating modes", True, "Conformal certifies that voltage scaling transitions preserve 100% boolean equivalence."),
              ("Synthesize separate netlists for each voltage", False, "A single physical netlist must support all DVFS modes."),
              ("Disable DVFS mode switching in firmware", False, "Firmware controls power scaling dynamically."),
              ("Delete level shifters on DVFS domains", False, "Level shifters are mandatory at voltage boundaries.")]),

            ("Isolation Control Signal Glitch Prevention Proof", "HIGH", "Low Power LEC",
             "Isolation enable net driven by un-registered combinational logic generated hazardous glitches during power-up sequence.",
             "// Warning: Isolation enable pin 'u_core/iso_en' driven by combinational AND gate\n// Hazard: Spurious mid-rail glitch possible during domain power transition",
             "Isolation control signals must be glitch-free and driven directly by glitchless always-on registers.",
             "verify_power_intent -glitch_free_iso\ncompare",
             [("Glitch Hazards", "1"), ("ISO Quality", "RISKY")], [("Glitch Hazards", "0"), ("ISO Quality", "ROBUST")],
             [("Verify isolation enable signals are driven by glitchless AON registers using verify_power_intent", True, "Glitchless isolation control ensures receiving active logic never sees spurious transitions during wake-up."),
              ("Add an inverter on the isolation control line", False, "Inverting control inverts sleep/wake timing."),
              ("Disable isolation checking during wake-up", False, "Wake-up glitches can corrupt CPU state machines."),
              ("Remove all isolation control logic", False, "Removing control disables power isolation.")]),

            ("Ground Bounce Multi-Domain Ground Invariance", "LOW", "Low Power LEC",
             "Dual VSS_CORE and VSS_PERIPHERAL ground rails verified connected to common analog substrate without logic short.",
             "// Info: Power intent models separate VSS ground domains\n// Result: EQUIVALENT boolean logic across ground boundaries",
             "Ground domain separation in UPF provides electrical noise isolation while preserving digital zero reference.",
             "verify_power_intent\ncompare",
             [("Ground Domains", "2"), ("Status", "VERIFIED")], [("Ground Domains", "2"), ("Status", "EQUIVALENT")],
             [("Run standard power intent verification across separate ground domains", True, "Formal power checks confirm ground domain boundaries are maintained without functional discrepancy."),
              ("Short digital ground to high voltage supply", False, "Shorting ground to supply causes dead shorts."),
              ("Delete ground definitions from UPF", False, "Ground intent must be declared for advanced nodes."),
              ("Float the peripheral ground rail", False, "Floating ground causes chip destruction.")]),

            ("Power-Gated RAM Macro Retention Pin Verification", "HIGH", "Low Power LEC",
             "512KB SRAM macro retention sleep pin (`RET_EN`) was left unconnected in Revised netlist during PnR routing.",
             "// Error: Macro 'u_cache/sram_512k' retention pin RET_EN is floating\n// Conformal UPF rule 'SRAM_RETENTION_CONNECT' failed",
             "Memory macros with retention modes must have their retention enable pins wired to dedicated always-on control logic.",
             "verify_power_intent -macro_pins\ncompare",
             [("Floating Macro Pins", "1"), ("SRAM Retention", "BROKEN")], [("Floating Macro Pins", "0"), ("SRAM Retention", "VERIFIED")],
             [("Check macro pin connectivity against UPF intent with verify_power_intent -macro_pins", True, "Verifying macro pins ensures memory sleep and retention pins are wired properly."),
              ("Delete the SRAM macro from the design", False, "Deleting memory destroys processor functionality."),
              ("Tie the SRAM retention pin to VDD permanently", False, "Tying to VDD forces permanent sleep mode."),
              ("Ignore macro pin violations in LEC", False, "Ignoring memory pin bugs causes data corruption on sleep.")]),

            ("Top-Level Power Intent Hierarchical Scoping Rule", "MEDIUM", "Low Power LEC",
             "Sub-block UPF power intent scope was misaligned with top-level SoC hierarchy instantiations.",
             "// Error: UPF scope '/PD_DSP' not found in top-level hierarchy 'soc_top/u_dsp_core'\n// LEC-UPF-018: Hierarchy scope mismatch",
             "Hierarchical UPF requires exact scope definition matching RTL instance paths using set_scope.",
             "read_power_intent -module dsp_core ./upf/dsp.upf\nread_power_intent -top soc_top ./upf/top.upf\nverify_power_intent",
             [("Scope Mismatches", "1"), ("UPF State", "INVALID")], [("Scope Mismatches", "0"), ("UPF State", "VALID")],
             [("Bind sub-module UPF files to proper instance scopes using read_power_intent -module", True, "Modular UPF scoping ensures sub-block power rules bind cleanly to top-level SoC instances."),
              ("Flatten all UPF files into a single un-scoped script", False, "Un-scoped UPF causes instance name collisions."),
              ("Delete sub-block power rules", False, "Deleting rules drops power gating for sub-modules."),
              ("Rename RTL instances to match wrong UPF scopes", False, "Modifying RTL to match broken scripts is bad practice.")])
        ]
    },
    {
        "id": "lec_scan_dft_bypass",
        "name": "Scan & DFT Logic Bypass Equivalence",
        "tagline": "Scan chain reordering, test mode pin clamping, scan compression decompressor bypass & MBIST isolation",
        "scenarios": [
            ("Scan Chain Reordering Invariance in Post-Route Netlist", "CRITICAL", "DFT Setup",
             "Innovus reordered 12,000 flip-flops in scan chains to optimize wire routing, failing functional equivalence without test mode pin constraints.",
             "// Non-equivalent compare points: 12,000 DFFs in scan chain\n// Root Cause: scan_enable=1 during compare; evaluating test shift data paths",
             "Scan chain connections are tested exclusively in manufacturing test mode. When verifying functional equivalence, tie scan_enable to 0.",
             "add_pin_constraints 0 scan_enable -both\nadd_pin_constraints 0 test_mode -both\nset_system_mode lec\ncompare",
             [("Non-Equiv DFFs", "12,000"), ("Status", "FAIL")], [("Non-Equiv DFFs", "0"), ("Status", "EQUIVALENT")],
             [("Constrain scan_enable and test_mode pins to 0 using add_pin_constraints", True, "Clamping scan_enable to 0 isolates scan shift routing and tests pure functional datapath logic."),
              ("Force Innovus to preserve original synthesis scan chain order", False, "Preserving scan order creates massive physical wire congestion."),
              ("Delete all scan chains from the physical netlist", False, "Deleting scan chains makes the fabricated chip untestable."),
              ("Invert the scan input pins on all registers", False, "Inverting scan pins breaks DFT test vectors.")]),

            ("Scan Compression Decompressor/Compactor Formal Bypass", "HIGH", "DFT Setup",
             "On-chip scan compression XOR decompressor network evaluated into functional data cones without test mode clamping.",
             "// Compare: 340 points non-equivalent on scan decompressor interface\n// Mismatch: Test compression logic active during functional compare",
             "On-chip scan compression logic must be isolated during functional LEC by clamping edt_mode / scan_compression_en to 0.",
             "add_pin_constraints 0 edt_mode -both\nadd_pin_constraints 0 scan_compression_en -both\nset_system_mode lec\ncompare",
             [("Decompressor Mismatches", "340"), ("Status", "FAIL")], [("Decompressor Mismatches", "0"), ("Status", "PASS")],
             [("Clamp scan compression mode pins to 0 using add_pin_constraints", True, "Clamping compression mode pins ensures XOR decompressor logic is bypassed during functional verification."),
              ("Remove scan decompressor logic from netlist", False, "Removing decompressor increases test time by 50x."),
              ("Tie compression test data inputs to constant 1", False, "Tying inputs does not bypass the test mode."),
              ("Disable compression checking in manufacturing test", False, "Compression is vital for factory ATE testers.")]),

            ("Memory BIST (MBIST) Collar Wrapper Mux Isolation", "HIGH", "DFT Setup",
             "MBIST test collar multiplexers on SRAM memory address inputs compared non-equivalent because mbist_en was unconstrained.",
             "// Non-equivalent compare points: 128 Address/Data pins on SRAM macros\n// Mismatch: MBIST pattern generator driving RAM inputs instead of functional bus",
             "MBIST multiplexers must be held in functional mode by constraining mbist_mode / mbist_en to 0.",
             "add_pin_constraints 0 mbist_en -both\nadd_pin_constraints 0 mbist_start -both\nset_system_mode lec\ncompare",
             [("RAM Pin Mismatches", "128"), ("Status", "FAIL")], [("RAM Pin Mismatches", "0"), ("Status", "EQUIVALENT")],
             [("Constrain MBIST enable pins to 0 with add_pin_constraints 0 mbist_en -both", True, "Clamping MBIST enable to 0 selects functional CPU/DMA bus access to memory macros."),
              ("Delete the MBIST collar from SRAM macros", False, "Deleting MBIST prevents memory manufacturing test."),
              ("Force MBIST to run continuously", False, "Continuous MBIST blocks normal processor access to memory."),
              ("Short MBIST test pins to ground inside SRAM RTL", False, "Modifying SRAM RTL corrupts standard vendor memory IP.")]),

            ("Boundary Scan IEEE 1149.1 TAP Controller Masking", "MEDIUM", "DFT Setup",
             "JTAG boundary scan TAP controller in Test-Logic-Reset state verified non-interfering with functional I/O pads.",
             "// Compare: All 180 I/O Pad Boundary Scan Cells\n// Result: EQUIVALENT (Boundary scan bypass cells transparent in functional mode)",
             "Holding JTAG TMS=1 and TRST_N=0 keeps the boundary scan TAP controller in Test-Logic-Reset mode, making I/O pads transparent.",
             "add_pin_constraints 0 trst_n -both\nadd_pin_constraints 1 tms -both\nset_system_mode lec\ncompare",
             [("Boundary Scan Cells", "180"), ("Status", "VERIFIED")], [("Boundary Scan Cells", "180"), ("Status", "EQUIVALENT")],
             [("Constrain JTAG TAP controller to Test-Logic-Reset mode using add_pin_constraints", True, "Holding TAP controller in reset ensures boundary scan data registers do not intercept chip pad signals."),
              ("Remove JTAG TAP controller from netlist", False, "Removing JTAG breaks board-level test and debug."),
              ("Tie JTAG TCK clock to 1 GHz", False, "TCK is a low-speed 20 MHz test clock."),
              ("Invert TDI test data input line", False, "Inverting TDI corrupts JTAG instruction decoding.")]),

            ("On-Chip Clock Controller (OCC) Test Mux Verification", "HIGH", "DFT Setup",
             "OCC test clock selection multiplexers evaluated between PLL functional clock and ATE scan clock without OCC mode constraint.",
             "// Compare: Clock root compare points in u_cts/occ_root_inst\n// Mismatch: ATE scan clock path active during compare",
             "OCC test mode select pins (occ_mode_en) must be constrained to 0 so the tool verifies the high-speed PLL clock branch.",
             "add_pin_constraints 0 occ_mode_en -both\nadd_pin_constraints 0 fast_capture_en -both\nset_system_mode lec\ncompare",
             [("OCC Clock Mismatches", "16"), ("Status", "FAIL")], [("OCC Clock Mismatches", "0"), ("Status", "PASS")],
             [("Clamp OCC test mode enable pins to 0 with add_pin_constraints", True, "Clamping OCC mode ensures functional PLL clock paths are selected for equivalence proofs."),
              ("Delete the OCC clock controller from the clock tree", False, "Deleting OCC prevents at-speed transition test."),
              ("Short PLL clock directly to ATE scan clock port", False, "Shorting clocks creates electrical clock conflicts."),
              ("Invert the OCC bypass select signal", False, "Inverting signal forces permanent test clock mode.")]),

            ("Dual-Rail Lockup Latch Scan Reordering Invariance", "LOW", "DFT Setup",
             "Lockup latches inserted between cross-clock-domain scan registers verified completely transparent in functional mode.",
             "// Info: 48 Lockup latches detected in scan chain\n// Result: EQUIVALENT (Lockup latches inactive when scan_enable=0)",
             "Lockup latches exist solely to prevent scan hold time violations during test shift mode; they have zero impact when scan_enable=0.",
             "add_pin_constraints 0 scan_enable -both\ncompare",
             [("Lockup Latches", "48"), ("Functional Impact", "ZERO")], [("Lockup Latches", "48"), ("Functional Impact", "ZERO")],
             [("Verify functional equivalence with scan_enable tied low", True, "Lockup latches are physically bypassed when scan_enable is 0."),
              ("Delete lockup latches from scan chains", False, "Deleting lockup latches causes scan shift hold violations on tester."),
              ("Replace lockup latches with flip-flops", False, "Flip-flops change scan chain cycle latency."),
              ("Invert the clock input to lockup latches", False, "Inverting clock breaks lockup latch half-cycle timing.")]),

            ("Logic BIST (LBIST) PRPG Pattern Generator Bypass", "HIGH", "DFT Setup",
             "Pseudo-Random Pattern Generator (PRPG) and MISR signature registers unconstrained during functional compare.",
             "// Non-equivalent compare points: 256 PRPG/MISR registers\n// Mismatch: Autonomous LBIST execution active",
             "LBIST controllers must be disabled during functional LEC by asserting lbist_en=0 and lbist_start=0.",
             "add_pin_constraints 0 lbist_en -both\nadd_pin_constraints 0 lbist_start -both\nset_system_mode lec\ncompare",
             [("LBIST Mismatches", "256"), ("Status", "FAIL")], [("LBIST Mismatches", "0"), ("Status", "PASS")],
             [("Clamp LBIST enable pins to 0 with add_pin_constraints", True, "Clamping LBIST enable isolates autonomous pseudo-random generators from functional logic."),
              ("Delete the LBIST engine from the chip", False, "Deleting LBIST removes automotive in-field self-test."),
              ("Force MISR signature register to zero", False, "Forcing signature destroys fault detection."),
              ("Run LBIST continuously during functional mode", False, "Continuous LBIST corrupts CPU execution.")]),

            ("IEEE 1500 Embedded Core Test Wrapper Masking", "MEDIUM", "DFT Setup",
             "IEEE 1500 wrapper boundary cells on embedded DSP core verified transparent in normal mission mode.",
             "// Compare: 512 Core Wrapper Cells in u_dsp/wrc_inst[*]\n// Result: EQUIVALENT (Wrapper bypass mode verified)",
             "Asserting IEEE 1500 `wrc_mode=0` and `wrc_select=0` ensures core test wrappers pass functional signals transparently.",
             "add_pin_constraints 0 wrc_mode -both\nadd_pin_constraints 0 wrc_select -both\nset_system_mode lec\ncompare",
             [("Wrapper Cells", "512"), ("Status", "VERIFIED")], [("Wrapper Cells", "512"), ("Status", "EQUIVALENT")],
             [("Constrain IEEE 1500 core wrapper control pins to 0", True, "Setting wrapper mode to 0 guarantees transparent chip mission mode operation."),
              ("Delete IEEE 1500 wrappers from IP blocks", False, "Deleting wrappers prevents modular core testing."),
              ("Short wrapper serial input to serial output", False, "Shorting test lines does not isolate parallel functional paths."),
              ("Invert the wrapper clock signal", False, "Inverting clock corrupts wrapper scan timing.")]),

            ("Analog Test Mux (AMUX) Isolation Pin Clamping", "LOW", "DFT Setup",
             "Analog test bus multiplexer pins verified isolated from internal ADC/DAC sensitive analog voltage nodes.",
             "// Compare: u_analog/amux_sel[3:0]\n// Result: EQUIVALENT (Analog test bus disconnected in mission mode)",
             "AMUX selector pins clamped to 0 isolate sensitive analog nodes from digital test bus noise.",
             "add_pin_constraints 0 amux_en -both\ncompare",
             [("AMUX Pins", "4"), ("Status", "ISOLATED")], [("AMUX Pins", "4"), ("Status", "EQUIVALENT")],
             [("Clamp AMUX test enable pins to 0", True, "Clamping AMUX disconnects external test probes during normal execution."),
              ("Connect AMUX to power supply", False, "Connecting AMUX to supply creates dead shorts."),
              ("Delete the AMUX from the netlist", False, "AMUX is needed for factory analog calibration."),
              ("Short analog inputs together", False, "Shorting analog inputs destroys signal accuracy.")]),

            ("Scan Shift Mode Dedicated Verification Run", "MEDIUM", "DFT Setup",
             "Dedicated DFT verification mode proving scan chains shift vectors from scan_in to scan_out without functional interference.",
             "// Dedicated Scan Shift Mode LEC:\n// scan_enable=1, test_mode=1\n// Result: All 64 Scan Chains verify 100% serial shift equivalence",
             "In scan shift LEC, constrain scan_enable=1 to formally verify that scan_in pins connect exclusively to scan_out through shift registers.",
             "add_pin_constraints 1 scan_enable -both\nadd_pin_constraints 1 test_mode -both\nset_system_mode lec\ncompare",
             [("Scan Chains", "64"), ("Shift Proof", "VERIFYING")], [("Scan Chains", "64"), ("Shift Proof", "EQUIVALENT")],
             [("Run dedicated scan shift LEC with scan_enable=1 to certify scan chain integrity", True, "Verifying scan shift mode proves all scan chains are structurally intact from scan_in to scan_out pins."),
              ("Force all scan registers to permanent 0", False, "Forcing to 0 prevents test vector shifting."),
              ("Short scan_in directly to scan_out", False, "Shorting bypasses the internal flip-flops."),
              ("Disable scan shift verification", False, "Scan shift proof guarantees zero physical scan chain breaks.")])
        ]
    },
    {
        "id": "lec_clock_gating_retiming",
        "name": "Clock Gating & Sequential Retiming",
        "tagline": "Integrated Clock Gating (ICG) latch-free proofs, clock cloning & pipelined retiming maps",
        "scenarios": [
            ("Integrated Clock Gating (ICG) Latch-Enable Formal Proof", "CRITICAL", "Clock Gating",
             "Synthesis replaced RTL clock enable muxes (`if (en) q <= d;`) with Integrated Clock Gating cells (`ICG_X4`), causing compare mismatches without clock gate mapping.",
             "// Compare: 4,500 DFFs driven by ICG cells in Revised netlist\n// Golden RTL models recirculating multiplexer feedback\n// State: Non-equivalent unless gated clock mapping is enabled",
             "Recirculating data enable muxes in RTL are mathematically identical to clock-gated registers when ICG cells have active-low latches.",
             "set_flatten_model -gated_clock\nmap_key_points\nset_system_mode lec\ncompare",
             [("ICG Compare Mismatches", "4,500"), ("Status", "FAIL")], [("ICG Compare Mismatches", "0"), ("Status", "EQUIVALENT")],
             [("Enable automatic clock gating transformation mapping with set_flatten_model -gated_clock", True, "Clock gating mapping proves that stopping the clock via ICG latches matches holding register values via recirculating multiplexers."),
              ("Delete all ICG cells and restore data muxes in PnR", False, "Restoring data muxes increases clock dynamic power by 40%."),
              ("Invert the ICG enable pin polarity", False, "Inverting enable polarity gates the clock during active cycles."),
              ("Disable clock gating verification in LEC", False, "Skipping ICG verification risks silicon clock gating glitch failures.")]),

            ("Multi-Stage Hierarchical Clock Gating Cloning Equivalence", "HIGH", "Clock Gating",
             "Innovus cloned a single root ICG cell into 8 distributed branch ICG cells to satisfy clock max_fanout rules.",
             "// Revised netlist contains 8 cloned ICG instances: u_cts/icg_branch_0..7\n// Golden netlist has 1 root ICG instance: u_ctrl/icg_root",
             "Clock gate cloning replicates enable logic across parallel trees without changing downstream register clocking behavior.",
             "set_flatten_model -gated_clock -seq_constant\nmap_key_points\nset_system_mode lec\ncompare",
             [("Cloned ICGs", "8"), ("Status", "UNMAPPED")], [("Cloned ICGs", "8"), ("Status", "EQUIVALENT")],
             [("Enable clock gate cloning analysis with set_flatten_model -gated_clock", True, "Conformal recognizes cloned ICG branches as functionally identical parallel clock drivers."),
              ("Force PnR to use only a single ICG cell", False, "A single ICG cell violates physical slew and capacitance DRCs."),
              ("Short all 8 ICG output clocks together", False, "Shorting clock driver outputs creates severe crowbar currents."),
              ("Delete the cloned ICG enable lines", False, "Deleting enable lines disables clock gating power savings.")]),

            ("Sequential Retiming Forward Pipeline Register Shift", "HIGH", "Retiming Proof",
             "Synthesis moved a pipeline register forward across an ALU multiplexer, changing register locations from inputs to output.",
             "// Non-equivalent compare points: 32 DFFs in u_alu/op_reg[*] shifted across MUX\n// Golden: 2x 32-bit registers before MUX; Revised: 1x 32-bit register after MUX",
             "Forward sequential retiming merges parallel input registers into a single output register; verify using synthesis FV_MAP.",
             "read_fv_map -retime ./synthesis/genus_retiming.map\nset_system_mode lec\ncompare",
             [("Retimed Points", "32"), ("Status", "FAIL")], [("Retimed Points", "0"), ("Status", "EQUIVALENT")],
             [("Ingest synthesis retiming map using read_fv_map -retime to prove sequential equivalence", True, "The FV retiming map allows Conformal to verify sequential transfer function invariance across retimed pipeline registers."),
              ("Disable pipeline retiming in synthesis", False, "Disabling retiming drops chip clock frequency by 15%."),
              ("Insert duplicate registers in RTL manually", False, "Manual RTL changes risk introducing pipeline mismatch bugs."),
              ("Ignore ALU output compare points", False, "Ignoring ALU outputs creates catastrophic verification gaps.")]),

            ("Valid-Ready Skid Buffer Register Retiming Equivalence", "MEDIUM", "Retiming Proof",
             "AXI-Stream skid buffer register retiming verified equivalent to baseline 2-stage FIFO without throughput loss.",
             "// Compare: u_axi/skid_buffer_inst (Forward & Backward Register Stages)\n// Result: EQUIVALENT (Zero bubble cycles, 100% throughput proven)",
             "Skid buffers decouple ready and valid timing paths; Conformal proves sequential cycle-by-cycle equivalence.",
             "set_flatten_model -seq_constant -gated_clock\ncompare",
             [("Skid Buffer FFs", "64"), ("Status", "VERIFYING")], [("Skid Buffer FFs", "64"), ("Status", "EQUIVALENT")],
             [("Execute sequential compare on skid buffer register logic", True, "Conformal verifies that skid buffer register forwarding logic preserves exact stream data ordering."),
              ("Replace skid buffer with a direct wire connection", False, "Direct wiring creates combinational timing loops."),
              ("Force ready signal permanently to 1", False, "Forcing ready drops data when receiver is busy."),
              ("Delete the skid buffer shadow registers", False, "Deleting shadow registers halves pipeline throughput.")]),

            ("Glitchless Clock Multiplexer Dynamic Switching Proof", "HIGH", "Clock Gating",
             "Glitch-free clock switch containing dual cross-coupled enable latches verified transparent to both reference clocks.",
             "// Compare: u_clkmux/glitchfree_switch_inst\n// Result: EQUIVALENT across both clk_fast and clk_slow modes",
             "Glitchless clock muxes prevent runt pulses during dynamic clock switching; formal equivalence proves state coverage.",
             "add_pin_constraints 0 clk_sel -both\ncompare\nadd_pin_constraints 1 clk_sel -both\ncompare",
             [("Glitchfree Mux", "1"), ("Modes Verified", "0/2")], [("Glitchfree Mux", "1"), ("Modes Verified", "2/2")],
             [("Verify glitchless clock mux under both clk_sel=0 and clk_sel=1 pin constraints", True, "Testing both select states proves glitchless clock multiplexing is functionally correct in all modes."),
              ("Replace glitchless mux with a simple combinational AND gate", False, "AND gates produce dangerous clock runt glitches."),
              ("Short both clock inputs together", False, "Shorting asynchronous clocks causes clock tree contention."),
              ("Disable clock multiplexer verification", False, "Clock switches must be verified to prevent silicon lockup.")]),

            ("Clock Divider Toggle Flip-Flop Equivalence", "MEDIUM", "Clock Gating",
             "Divide-by-2 clock divider implemented with inverted feedback DFF verified equivalent to behavioral clock toggle RTL.",
             "// Compare: u_div/clk_div2_reg (Toggle Flip-Flop)\n// Result: EQUIVALENT (50% duty cycle divided clock proven)",
             "A toggle flip-flop with D = ~Q divides clock frequency by 2; Conformal proves boolean state toggling matches behavioral models.",
             "compare",
             [("Clock Divider FFs", "1"), ("Status", "VERIFIED")], [("Clock Divider FFs", "1"), ("Status", "EQUIVALENT")],
             [("Run standard compare on toggle clock divider register", True, "Conformal proves D = ~Q sequential flip-flop matches RTL clock division logic."),
              ("Replace clock divider with an external crystal", False, "On-chip clock dividers provide internal divided clocks."),
              ("Invert the reset polarity on the divider", False, "Inverting reset changes initial clock phase."),
              ("Set divider output to constant 1", False, "Constant output stops the divided clock tree.")]),

            ("Multicycle Path Register Setup/Hold Invariance", "LOW", "Clock Gating",
             "2-cycle multicycle path with clock enable active every second cycle verified functionally equivalent to RTL intent.",
             "// Compare: u_dsp/mcp_stage2_reg[*]\n// Result: EQUIVALENT (Clock enable matches 2-cycle multi-rate transfer)",
             "Multicycle paths constrained in SDC operate under multi-cycle clock enable logic that Conformal verifies formally.",
             "compare",
             [("MCP Registers", "64"), ("Status", "VERIFIED")], [("MCP Registers", "64"), ("Status", "EQUIVALENT")],
             [("Execute compare on multicycle path register cones", True, "Conformal proves multicycle clock-enabled registers preserve data across designated clock cycles."),
              ("Delete multicycle clock enable logic", False, "Deleting enable logic causes data corruption on cycle 1."),
              ("Force all multicycle paths to 1-cycle", False, "1-cycle operation creates massive setup timing violations."),
              ("Ignore multicycle registers during LEC", False, "MCP registers must be verified formally.")]),

            ("Asynchronous FIFO Gray Pointer Synchronization Invariance", "HIGH", "Clock Gating",
             "Gray-code write pointer increment and 2-FF synchronizer stages verified preserving 1-bit-change-per-cycle transfer.",
             "// Compare: u_fifo/wptr_gray_reg[5:0] & sync_rptr_reg[5:0]\n// Result: EQUIVALENT (Gray encoding and register stages proven)",
             "Gray pointer generation and synchronizer stages are sequential state points that Conformal verifies against Golden RTL.",
             "add_compared_points u_fifo/*reg*\ncompare",
             [("FIFO Pointer Bits", "6"), ("Sync Stages", "2")], [("FIFO Pointer Bits", "6"), ("Sync Stages", "2")],
             [("Add FIFO pointer and synchronizer registers to compare list and execute compare", True, "Conformal certifies that binary-to-Gray conversion and multi-stage synchronizers match RTL architecture."),
              ("Replace Gray pointers with binary counters", False, "Binary counters across asynchronous boundaries cause CDC metastability glitches."),
              ("Short synchronizer stages into a single register", False, "1-FF synchronizers have unacceptable MTBF failure rates."),
              ("Delete the asynchronous FIFO", False, "Asynchronous FIFOs are required for cross-clock data transfer.")]),

            ("Register File Multi-Port Read/Write Address Decoding Equivalence", "MEDIUM", "Clock Gating",
             "32x32-bit register file with 2 read ports and 1 write port verified against synthesizable mux array netlist.",
             "// Compare: 1,024 Register File Storage Bits (32 Words x 32 Bits)\n// Result: EQUIVALENT (All 1,024 storage latches/FFs match Golden)",
             "Multi-port register file decoding logic matches discrete flip-flop array models when address decoders are mapped.",
             "set_flatten_model -seq_constant\ncompare",
             [("Regfile Bits", "1,024"), ("Status", "VERIFYING")], [("Regfile Bits", "1,024"), ("Status", "EQUIVALENT")],
             [("Run compare on register file memory storage points", True, "Conformal proves multi-port read/write address decoding matches Golden RTL storage arrays."),
              ("Treat register file as an unverified blackbox", False, "Register files must be verified to ensure processor core correctness."),
              ("Short all 32 register words together", False, "Shorting words destroys register addressability."),
              ("Disable write enable checks", False, "Write enable logic is vital to prevent register corruption.")]),

            ("Dual-Edge Clocking (DDR) Flip-Flop Mapping", "HIGH", "Clock Gating",
             "DDR interface utilizing positive-edge and negative-edge triggered registers mapped cleanly under dual-phase modeling.",
             "// Compare: u_ddr/tx_pos_reg[*] (Posedge) & tx_neg_reg[*] (Negedge)\n// Result: EQUIVALENT (Double data rate transfer verified)",
             "Dual-edge clocking transfers data on both clock edges; Conformal models rising and falling edge Key Points independently.",
             "set_flatten_model -dual_edge\nmap_key_points\ncompare",
             [("DDR Registers", "32"), ("Status", "VERIFIED")], [("DDR Registers", "32"), ("Status", "EQUIVALENT")],
             [("Enable dual-edge clock modeling with set_flatten_model -dual_edge", True, "Dual-edge modeling allows Conformal to verify both posedge and negedge registers in DDR interfaces."),
              ("Convert all negedge registers to posedge in RTL", False, "Converting edges halves DDR transmission bandwidth."),
              ("Invert the DDR clock externally", False, "Inverting clock swaps odd and even data words."),
              ("Ignore negedge register compare points", False, "Ignoring negedge registers skips half of all DDR data.")]),
        ]
    },
    {
        "id": "lec_debug_eco",
        "name": "Non-Equivalent Debug & Golden Functional ECO",
        "tagline": "Counter-example diagnosis, error cone isolation, automated functional ECO patches & spare cell mapping",
        "scenarios": [
            ("Counter-Example Vector Diagnosis & Error Cone Isolation", "CRITICAL", "Non-Equiv Debug",
             "Conformal flags a non-equivalent compare point at `u_ctrl/fsm_next_state[2]`; engineer needs to diagnose the root cause.",
             "// Compare Results: 1 NON-EQUIVALENT compare point\n// Failing Point: u_ctrl/fsm_next_state[2] (DFF)\n// Counter-Example: {mode=2'b10, timeout=1'b1, ack=1'b0} -> Golden=1, Revised=0",
             "Counter-example vectors pinpoint the exact input stimulus where Golden and Revised logic cones diverge; use diagnose to isolate the faulty gate.",
             "diagnose -point u_ctrl/fsm_next_state[2] -view\nset_system_mode lec",
             [("Failing Points", "1"), ("Root Cause", "UNKNOWN")], [("Failing Points", "1"), ("Root Cause", "ISOLATED (NAND2 Pin A)")],
             [("Run diagnose -point to display counter-example vector and isolate the error gate cone", True, "The diagnose command highlights the exact combinational gate where boolean evaluation differs between netlists."),
              ("Delete the failing register from the netlist", False, "Deleting failing registers hides design bugs."),
              ("Invert the output of the failing gate randomly", False, "Random patching risks introducing further subtle errors."),
              ("Ignore the single non-equivalent point", False, "A single non-equivalent point will crash physical silicon.")]),

            ("Automated Functional ECO Patch Generation (`write_eco_script`)", "CRITICAL", "Functional ECO",
             "RTL bug fix in ALU control logic requires generating a minimal, surgical gate-level ECO patch for Innovus P&R.",
             "// Golden: Modified RTL with bug fix in u_alu/overflow_detect\n// Revised: Post-route tapeout netlist\n// Target: Generate minimal spare cell patch script",
             "Conformal ECO engine computes the boolean difference between Golden and Revised cones and synthesizes a minimal ECO patch.",
             "write_eco_script -replace -eco_dir ./eco_patch_r1 -format innovus\n// Generated file: eco_patch_r1/eco_patch.tcl",
             [("Manual ECO Time", "3 Days"), ("Gate Disruption", "HIGH")], [("Automated ECO Time", "45 Seconds"), ("Gate Disruption", "MINIMAL (3 Gates)")],
             [("Generate automated Innovus ECO patch using write_eco_script", True, "write_eco_script outputs optimized Tcl commands (eco_change_cell, eco_add_repeater) to patch the netlist surgically."),
              ("Re-synthesize the entire chip from scratch in Genus", False, "Full re-synthesis requires re-running full PnR and invalidates post-route timing closure."),
              ("Hand-edit the 100MB Verilog netlist in a text editor", False, "Hand-editing large netlists is dangerous and prone to syntax/logical errors."),
              ("Modify the physical GDSII layout polygons manually", False, "GDSII polygon hacking violates LVS and DRC integrity.")]),

            ("Pre-Mask vs Post-Mask Metal-Only Spare Cell Allocation", "HIGH", "Functional ECO",
             "Post-mask functional bug fix must be implemented using ONLY pre-placed spare gates (NAND2, NOR2, INVERTER) to avoid base wafer re-spin.",
             "// Spare Cell Budget: 420 Spare Gates allocated in floorplan whitespace\n// Conformal ECO mapping: Patch requires 2x NAND2_SPARE and 1x INV_SPARE",
             "In post-mask ECOs, map patch logic exclusively to pre-instantiated spare cells via map_spare_cells to restrict changes to metal masks.",
             "read_spare_cells ./pnr/spare_cell_list.txt\nmap_spare_cells -eco_dir ./metal_eco_patch\nwrite_eco_script -spare_only -format innovus",
             [("Mask Re-spin Cost", "$2,400,000"), ("Turnaround", "12 Weeks")], [("Mask Re-spin Cost", "$180,000 (Metal Only)"), ("Turnaround", "2 Weeks")],
             [("Map ECO logic to pre-placed spare cells using read_spare_cells and write_eco_script -spare_only", True, "Spare-cell mapping limits ECO changes strictly to upper metal masks, saving millions in base wafer fabrication costs."),
              ("Instantiate new standard cells in empty floorplan sites", False, "Adding new base cells requires modifying FEOL diffusion/poly masks ($2M+)."),
              ("Cancel the tapeout and redesign the entire ASIC", False, "Metal ECOs allow fast silicon bug remediation."),
              ("Ignore the functional bug in silicon", False, "Shipping chips with known silicon bugs leads to customer product recalls.")]),

            ("Logic Inversion Bubble Push Proof", "LOW", "Non-Equiv Debug",
             "Synthesis transformed an AND-NOR cone into an OR-NAND cone via De Morgan's laws; proven equivalent.",
             "// Golden: ! ( (A & B) | (C & D) )\n// Revised: (!A | !B) & (!C | !D)\n// Result: EQUIVALENT (De Morgan bubble push verified)",
             "De Morgan transformations rearrange inverters and gate primitives without changing boolean transfer functions.",
             "compare",
             [("Logic Gates", "3"), ("Boolean Function", "NOR-AND")], [("Logic Gates", "3"), ("Boolean Function", "EQUIVALENT")],
             [("Run standard compare on bubble-pushed logic cones", True, "Conformal's boolean solver proves De Morgan gate transformations automatically."),
              ("Force synthesis to disable De Morgan transformations", False, "Disabling De Morgan increases cell count and delay."),
              ("Insert double inverters on all inputs", False, "Double inverters waste area and delay."),
              ("Invert the output pin polarity manually", False, "Inverting output inverts functional polarity.")]),

            ("Unmapped Key Point Root Cause Isolation", "HIGH", "Non-Equiv Debug",
             "14 flip-flops remained unmapped after automatic mapping heuristics; engineer needs to isolate if cause is pruning or renaming.",
             "// Unmapped Points: 14 Golden DFFs in u_video/gamma_lut_reg[*]\n// Report: report_unmapped_points -golden -summary",
             "The report_unmapped_points command categorizes unmapped points into unreachable, constant, or unmapped fanin categories.",
             "report_unmapped_points -golden -detailed > reports/unmapped_golden.rpt\nreport_unmapped_points -revised -detailed > reports/unmapped_revised.rpt",
             [("Unmapped Points", "14"), ("Root Cause", "UNKNOWN")], [("Unmapped Points", "0 (Mapped as Const 0)"), ("Root Cause", "RESOLVED")],
             [("Analyze unmapped points with report_unmapped_points -detailed to determine pruning vs naming causes", True, "Detailed unmapped reporting isolates whether registers were pruned as constants or misnamed during synthesis."),
              ("Delete all unmapped registers from the Golden RTL", False, "Deleting registers breaks RTL testbench simulation."),
              ("Add 14 dummy registers in Revised netlist", False, "Adding dummy registers creates unused silicon area."),
              ("Bypass unmapped register checks during tapeout signoff", False, "Unmapped registers can hide disconnected logic cones.")]),

            ("Cone-of-Logic Fanin/Fanout Depth Tracing", "MEDIUM", "Non-Equiv Debug",
             "Complex 48-level combinational arithmetic cone failing equivalence; trace logic depth to identify divergence stage.",
             "// Diagnostic Cone: 48 Logic Levels between reg_a and reg_b\n// Divergence Point: Level 14 (Multiplexer select line polarity)",
             "Tracing logic cone depth with report_cone isolates the exact intermediate net where Golden and Revised logic diverge.",
             "report_cone -point u_alu/failing_endpoint_reg/D -fanin -level 20\ndiagnose",
             [("Diagnostic Depth", "48 Levels"), ("Root Cause", "OBSCURE")], [("Diagnostic Depth", "Level 14"), ("Root Cause", "ISOLATED")],
             [("Trace fanin cone depth using report_cone to pinpoint intermediate logic divergence", True, "Fanin cone tracing narrows down complex deep logic cones to the earliest divergent net."),
              ("Short all intermediate logic levels together", False, "Shorting levels destroys combinational computation."),
              ("Break the cone into 48 separate physical clock domains", False, "Adding clock domains creates clock routing chaos."),
              ("Disable deep cone analysis in Conformal", False, "Deep cones must be verified to guarantee math accuracy.")]),

            ("Inversion Error Auto-Correction Patch", "MEDIUM", "Functional ECO",
             "A missing inverter on an interrupt active-low polarity pin (`intr_n`) resolved via 1-gate in-place inverter ECO.",
             "// Non-equivalent compare point: u_irq/intr_out_n\n// Error: Missing inversion on output pin\n// ECO Solution: Swap buffer BUFX2 -> Inverter INVX2 on existing footprint",
             "Simple polarity inversions are fixed surgically by swapping a non-inverting buffer to an inverter on the exact physical footprint.",
             "eco_change_cell -instance u_irq/u_buf_out -cell INVX2\nwrite_eco_script -format innovus",
             [("ECO Gate Count", "1 Cell Swap"), ("Wire Rerouting", "0 Wires")], [("ECO Gate Count", "1 Cell Swap"), ("Wire Rerouting", "0 Wires")],
             [("Execute in-place cell swap (BUFX2 -> INVX2) via eco_change_cell", True, "Footprint-matched in-place cell swapping fixes polarity bugs with zero placement displacement and zero wire re-routing."),
              ("Re-route the entire interrupt controller block", False, "Full block re-routing risks creating new DRC and timing violations."),
              ("Invert the interrupt pin inside software device drivers", False, "Software workarounds are unacceptable when hardware ECOs are available."),
              ("Change the printed circuit board wiring", False, "PCB changes cannot fix on-chip internal register bugs.")]),

            ("Golden Formal Verification Signoff Quality Report Package", "HIGH", "LEC Signoff",
             "Final tapeout signoff audit requiring zero unmapped points, zero non-equivalent points, and 100% formal compare completeness.",
             "// Conformal Signoff Summary:\n// Total Compare Points: 142,580\n// Equivalent: 142,580 (100.0%)\n// Non-Equivalent: 0 (0.0%)\n// Unmapped: 0 (0.0%)\n// Signoff Status: FORMALLY CERTIFIED",
             "Executive signoff requires executing add_compared_points -all, compare, and generating formal audit logs for foundry review.",
             "add_compared_points -all\ncompare\nreport_compare_data -class {non_equivalent unmapped} -out_file reports/lec_signoff_audit.rpt",
             [("Audit Completeness", "94%"), ("Signoff Status", "PENDING")], [("Audit Completeness", "100%"), ("Signoff Status", "PASSED (FORMAL SIGNOFF)")],
             [("Execute full compare on all points and export report_compare_data signoff package", True, "Full compare data export provides the mathematical certification required for tapeout signoff."),
              ("Sign off tapeout with 5 unresolved non-equivalent points", False, "Shipping with non-equivalent points guarantees silicon failure."),
              ("Delete failing points from the report script", False, "Falsifying signoff reports is a catastrophic engineering violation."),
              ("Use gate-level simulation instead of formal LEC", False, "Simulation cannot achieve 100% state coverage for billions of states.")]),

            ("Hierarchical Sub-Block Formal Verification Signoff", "MEDIUM", "LEC Signoff",
             "SoC top-level verification partitioned into hierarchical sub-blocks (CPU, GPU, DSP, NOC) for distributed server farm compute.",
             "// Hierarchical Signoff Run:\n// Block 1 (PD_CPU): 48,000 Points -> EQUIVALENT\n// Block 2 (PD_GPU): 62,000 Points -> EQUIVALENT\n// Block 3 (PD_NOC): 32,580 Points -> EQUIVALENT",
             "Hierarchical LEC verifies sub-blocks in parallel and blackboxes verified sub-blocks during top-level interconnect compare.",
             "set_flatten_model -gated_clock\nverify_hierarchical_design -blocks {cpu_top gpu_top noc_top}\ncompare",
             [("Top-Level Compute Time", "14 Hours"), ("Memory", "64 GB")], [("Distributed Compute Time", "45 Minutes"), ("Memory", "8 GB / Core")],
             [("Run hierarchical sub-block formal verification using verify_hierarchical_design", True, "Hierarchical verification reduces runtime by 10x while maintaining 100% formal proof rigor."),
              ("Flatten the entire 500-million gate SoC into a single run", False, "Full-chip flattening causes server memory exhaustion and long timeouts."),
              ("Skip top-level interconnect verification", False, "Interconnect pins must be verified formally."),
              ("Disable sub-block blackbox abstraction", False, "Blackboxing verified blocks accelerates top-level runs.")]),

            ("Multi-Tool SPEF Correlation vs LEC Invariance", "LOW", "LEC Signoff",
             "Verifying that parasitic SPEF back-annotation in STA tools does not alter formal digital netlist topology.",
             "// Info: Parasitic SPEF annotated in Tempus for timing\n// Conformal Proof: Physical parasitics have zero impact on boolean netlist logic",
             "SPEF contains analog parasitic resistances and capacitances; formal LEC operates purely on discrete boolean netlist graphs.",
             "compare",
             [("Parasitic Elements", "1.4 Million RC"), ("Boolean State", "INVARIANT")], [("Parasitic Elements", "1.4 Million RC"), ("Boolean State", "EQUIVALENT")],
             [("Confirm formal boolean equivalence is independent of physical SPEF parasitics", True, "Formal LEC proves logical correctness independently of electrical parasitics, while STA verifies timing closure."),
              ("Load SPEF parasitics into Conformal LEC", False, "Conformal is a boolean formal engine, not a circuit simulator."),
              ("Remove all parasitic capacitances from silicon", False, "Physical parasitics cannot be removed from real silicon."),
              ("Substitute STA timing reports for formal LEC proofs", False, "STA checks timing delays, not boolean functional equivalence.")])
        ]
    }
]

# Generate TypeScript code
out_ts = """export interface ConformalMetric {
  label: string;
  val: string;
}

export interface ConformalScenarioOption {
  id: string;
  label: string;
  correct: boolean;
  explanation: string;
}

export interface ConformalScenario {
  id: number;
  domainId: string;
  domainName: string;
  title: string;
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  stageName: string;
  symptom: string;
  logSnippet: string;
  principle: string;
  remedyTcl: string;
  beforeMetrics: ConformalMetric[];
  afterMetrics: ConformalMetric[];
  options: ConformalScenarioOption[];
}

export interface ConformalDomain {
  id: string;
  name: string;
  tagline: string;
}

export const CONFORMAL_DOMAINS: ConformalDomain[] = [
"""

for dom in DOMAINS:
    out_ts += f"""  {{
    "id": "{dom['id']}",
    "name": "{dom['name']}",
    "tagline": "{dom['tagline']}"
  }},\n"""

out_ts += "];\n\nexport const CONFORMAL_SCENARIOS: ConformalScenario[] = [\n"

scenario_id = 0
for dom in DOMAINS:
    for item in dom["scenarios"]:
        title, severity, stageName, symptom, logSnippet, principle, remedyTcl, beforeMetrics, afterMetrics, options = item
        
        opt_list = []
        for opt in options:
            opt_list.append({
                "id": opt[0].lower() if len(opt[0])==1 else ("a" if opt == options[0] else ("b" if opt == options[1] else ("c" if opt == options[2] else "d"))),
                "label": opt[0] if len(opt)==3 and len(opt[0])>1 else opt[1],
                "correct": opt[1] if len(opt)==3 and len(opt[0])>1 else opt[2],
                "explanation": opt[2] if len(opt)==3 and len(opt[0])>1 else opt[3]
            })
            # Fix options format
            if len(opt) == 3:
                lbl, corr, exp = opt
                opt_id = "a" if opt == options[0] else ("b" if opt == options[1] else ("c" if opt == options[2] else "d"))
                opt_dict = {"id": opt_id, "label": lbl, "correct": corr, "explanation": exp}
            else:
                opt_dict = {"id": opt[0], "label": opt[1], "correct": opt[2], "explanation": opt[3]}
        
        b_metrics = [{"label": m[0], "val": m[1]} for m in beforeMetrics]
        a_metrics = [{"label": m[0], "val": m[1]} for m in afterMetrics]
        
        formatted_options = []
        letters = ["a", "b", "c", "d"]
        for idx, o in enumerate(options):
            formatted_options.append({
                "id": letters[idx],
                "label": o[0],
                "correct": o[1],
                "explanation": o[2]
            })
        
        scenario_obj = {
            "id": scenario_id,
            "domainId": dom["id"],
            "domainName": dom["name"],
            "title": title,
            "severity": severity,
            "stageName": stageName,
            "symptom": symptom,
            "logSnippet": logSnippet,
            "principle": principle,
            "remedyTcl": remedyTcl,
            "beforeMetrics": b_metrics,
            "afterMetrics": a_metrics,
            "options": formatted_options
        }
        
        out_ts += "  " + json.dumps(scenario_obj, indent=2).replace("\n", "\n  ") + ",\n"
        scenario_id += 1

out_ts += "];\n"

with open("src/lib/conformal-scenarios-data.ts", "w") as f:
    f.write(out_ts)

print(f"Total raw scenarios generated: {scenario_id}")
