"""
workers/engines/flow/steps/yosys_step.py
Hermetic Logic Synthesis Step using Yosys.

Fail-closed: missing yosys or missing netlist → status=failed unless ACE_FLOW_MOCK=1.
"""
from __future__ import annotations

import os
import re
from typing import Any

from workers.engines.flow.mock_mode import allow_mock
from workers.engines.flow.state import DesignState
from workers.engines.flow.step import FlowStep


class YosysSynthesisStep(FlowStep):
    name = "yosys_synthesis"
    description = "Logic synthesis & gate-mapping using Yosys"

    def run(
        self,
        state: DesignState,
        work_dir: str,
        config: dict[str, Any],
    ) -> DesignState:
        output_netlist = os.path.join(work_dir, f"synthesis_{state.design_name}.v")
        script_file = os.path.join(work_dir, "synth.ys")
        log_file = "yosys.log"
        mock = allow_mock(config)

        rtl_read_cmds = [f"read_verilog -sv {rtl}" for rtl in state.rtl_files]

        liberty = config.get("liberty_file")
        map_cmds: list[str] = []
        if liberty:
            map_cmds.append(f"dfflibmap -liberty {liberty}")
            map_cmds.append(f"abc -liberty {liberty}")
        else:
            map_cmds.append("opt")

        script_lines = [
            "# Auto-generated by AceFlow YosysSynthesisStep",
            *rtl_read_cmds,
            f"hierarchy -check -top {state.design_name}",
            f"synth -top {state.design_name}",
            *map_cmds,
            "opt",
            f"write_verilog -noattr {output_netlist}",
            "stat",
        ]

        with open(script_file, "w", encoding="utf-8") as f:
            f.write("\n".join(script_lines) + "\n")

        yosys_bin = config.get("yosys_bin", "yosys")
        exit_code, elapsed = self.run_command(
            [yosys_bin, "-s", script_file],
            work_dir=work_dir,
            log_file=log_file,
        )

        metrics = dict(state.metrics)
        log_path = os.path.join(work_dir, log_file)
        cell_count = 0
        if os.path.exists(log_path):
            with open(log_path, "r", encoding="utf-8", errors="ignore") as lf:
                for line in lf:
                    if "Number of cells:" in line:
                        match = re.search(r"Number of cells:\s+(\d+)", line)
                        if match:
                            cell_count = int(match.group(1))

        status = "success" if exit_code == 0 and os.path.exists(output_netlist) else "failed"

        if not os.path.exists(output_netlist):
            if mock:
                with open(output_netlist, "w", encoding="utf-8") as nf:
                    nf.write(
                        f"// ACE_FLOW_MOCK placeholder netlist — not real synthesis\n"
                        f"module {state.design_name}();\nendmodule\n"
                    )
                cell_count = int(config.get("mock_cell_count", 1540))
                status = "success"
                metrics["synthesis_note"] = "mock_mode"
            else:
                with open(log_path, "a", encoding="utf-8") as lf:
                    lf.write(
                        "\n[AceFlow] Yosys did not produce a netlist. "
                        "Install yosys on PATH or set ACE_FLOW_MOCK=1 for demos.\n"
                    )

        metrics["synthesis_cell_count"] = cell_count
        metrics["synthesis_elapsed_s"] = round(elapsed, 2)

        artifacts = list(state.artifacts)
        artifacts.extend([script_file, log_path])
        if os.path.exists(output_netlist):
            artifacts.append(output_netlist)

        return state.clone(
            step_id=self.step_id,
            netlist=output_netlist if os.path.exists(output_netlist) else state.netlist,
            metrics=metrics,
            artifacts=tuple(artifacts),
            status=status,
            elapsed_seconds=state.elapsed_seconds + elapsed,
        )
